### ISSUE TITLE
OMV6 - Error changing shared folders privileges

### ISSUE THREAD

**Issue by ghost** [openmediavault/openmediavault#1260]
Hi, i have few bugs, i want to report about it, to make your product better.
OMV version:  6.0.18-1 (Shaitan)
Kernel: Linux 5.16.0-0.bpo.4-amd64 
Demonsration:
![R0E89w4OCg](https://user-images.githubusercontent.com/20506433/160232169-c1b8788f-07f7-45bd-afed-463930ce4b59.gif)
Error:
```
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; omv-salt deploy run --no-color fstab 2>&1' with exit code '1': debian:
----------
          ID: create_filesystem_mountpoint_b75f47bd-e32c-4358-b812-04be4195922c
    Function: file.accumulated
      Result: True
     Comment: Accumulator create_filesystem_mountpoint_b75f47bd-e32c-4358-b812-04be4195922c for file /etc/fstab was charged by text
     Started: 04:58:18.586592
    Duration: 0.88 ms
     Changes:
----------
          ID: mount_filesystem_mountpoint_b75f47bd-e32c-4358-b812-04be4195922c
    Function: mount.mounted
        Name: /srv/dev-disk-by-uuid-92bfd28d-0546-4c0a-93f3-3869a694f885
      Result: True
     Comment: Target was already mounted
     Started: 04:58:18.588087
    Duration: 73.343 ms
     Changes:
              ----------
              umount:
                  Forced remount because options (user_xattr) changed
----------
          ID: create_bind_mountpoint_74a68ae9-fddb-41d7-be3f-6762a92fa46d
    Function: file.accumulated
      Result: True
     Comment: Accumulator create_bind_mountpoint_74a68ae9-fddb-41d7-be3f-6762a92fa46d for file /etc/fstab was charged by text
     Started: 04:58:18.661708
    Duration: 1.454 ms
     Changes:
----------
          ID: mount_bind_mountpoint_74a68ae9-fddb-41d7-be3f-6762a92fa46d
    Function: mount.mounted
        Name: /export/test
      Result: True
     Comment: Target was already mounted
     Started: 04:58:18.663497
    Duration: 13.753 ms
     Changes:
----------
          ID: unmount_sftp_mountpoint_d88cf5f1-bd6a-467b-b1aa-e3153b7cf8c0
    Function: mount.unmounted
        Name: /sftp/connected/test
      Result: False
     Comment: umount: /test/: not mounted.. fstab entry not found
     Started: 04:58:18.677625
    Duration: 36.088 ms
     Changes:
----------
          ID: remove_openmediavault_dir_d88cf5f1-bd6a-467b-b1aa-e3153b7cf8c0
    Function: file.absent
        Name: /sftp/connected/test
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/modules/file.py", line 4118, in remove
                  shutil.rmtree(path)
                File "/usr/lib/python3.9/shutil.py", line 722, in rmtree
                  onerror(os.rmdir, path, sys.exc_info())
                File "/usr/lib/python3.9/shutil.py", line 720, in rmtree
                  os.rmdir(path)
              OSError: [Errno 16] Device or resource busy: '/sftp/connected/test'

              During handling of the above exception, another exception occurred:

              Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 2171, in call
                  ret = self.states[cdata["full"]](
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 1235, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2268, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2283, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2316, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/file.py", line 1917, in absent
                  __salt__["file.remove"](name)
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 1235, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2268, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2283, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/modules/file.py", line 4121, in remove
                  raise CommandExecutionError("Could not remove '{}': {}".format(path, exc))
              salt.exceptions.CommandExecutionError: Could not remove '/sftp/connected/test': [Errno 16] Device or resource busy: '/sftp/connected/test'
     Started: 04:58:18.714094
    Duration: 7.677 ms
     Changes:
----------
          ID: append_fstab_entries
    Function: file.blockreplace
        Name: /etc/fstab
      Result: True
     Comment: No changes needed to be made
     Started: 04:58:18.722643
    Duration: 5.823 ms
     Changes:

Summary for debian
------------
Succeeded: 5 (changed=1)
Failed:    2
------------
Total states run:     7
Total run time: 139.018 ms

OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; omv-salt deploy run --no-color fstab 2>&1' with exit code '1': debian:
----------
          ID: create_filesystem_mountpoint_b75f47bd-e32c-4358-b812-04be4195922c
    Function: file.accumulated
      Result: True
     Comment: Accumulator create_filesystem_mountpoint_b75f47bd-e32c-4358-b812-04be4195922c for file /etc/fstab was charged by text
     Started: 04:58:18.586592
    Duration: 0.88 ms
     Changes:
----------
          ID: mount_filesystem_mountpoint_b75f47bd-e32c-4358-b812-04be4195922c
    Function: mount.mounted
        Name: /srv/dev-disk-by-uuid-92bfd28d-0546-4c0a-93f3-3869a694f885
      Result: True
     Comment: Target was already mounted
     Started: 04:58:18.588087
    Duration: 73.343 ms
     Changes:
              ----------
              umount:
                  Forced remount because options (user_xattr) changed
----------
          ID: create_bind_mountpoint_74a68ae9-fddb-41d7-be3f-6762a92fa46d
    Function: file.accumulated
      Result: True
     Comment: Accumulator create_bind_mountpoint_74a68ae9-fddb-41d7-be3f-6762a92fa46d for file /etc/fstab was charged by text
     Started: 04:58:18.661708
    Duration: 1.454 ms
     Changes:
----------
          ID: mount_bind_mountpoint_74a68ae9-fddb-41d7-be3f-6762a92fa46d
    Function: mount.mounted
        Name: /export/test
      Result: True
     Comment: Target was already mounted
     Started: 04:58:18.663497
    Duration: 13.753 ms
     Changes:
----------
          ID: unmount_sftp_mountpoint_d88cf5f1-bd6a-467b-b1aa-e3153b7cf8c0
    Function: mount.unmounted
        Name: /sftp/connected/test
      Result: False
     Comment: umount: /test/: not mounted.. fstab entry not found
     Started: 04:58:18.677625
    Duration: 36.088 ms
     Changes:
----------
          ID: remove_openmediavault_dir_d88cf5f1-bd6a-467b-b1aa-e3153b7cf8c0
    Function: file.absent
        Name: /sftp/connected/test
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/modules/file.py", line 4118, in remove
                  shutil.rmtree(path)
                File "/usr/lib/python3.9/shutil.py", line 722, in rmtree
                  onerror(os.rmdir, path, sys.exc_info())
                File "/usr/lib/python3.9/shutil.py", line 720, in rmtree
                  os.rmdir(path)
              OSError: [Errno 16] Device or resource busy: '/sftp/connected/test'

              During handling of the above exception, another exception occurred:

              Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 2171, in call
                  ret = self.states[cdata["full"]](
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 1235, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2268, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2283, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2316, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/file.py", line 1917, in absent
                  __salt__["file.remove"](name)
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 1235, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2268, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2283, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/modules/file.py", line 4121, in remove
                  raise CommandExecutionError("Could not remove '{}': {}".format(path, exc))
              salt.exceptions.CommandExecutionError: Could not remove '/sftp/connected/test': [Errno 16] Device or resource busy: '/sftp/connected/test'
     Started: 04:58:18.714094
    Duration: 7.677 ms
     Changes:
----------
          ID: append_fstab_entries
    Function: file.blockreplace
        Name: /etc/fstab
      Result: True
     Comment: No changes needed to be made
     Started: 04:58:18.722643
    Duration: 5.823 ms
     Changes:

Summary for debian
------------
Succeeded: 5 (changed=1)
Failed:    2
------------
Total states run:     7
Total run time: 139.018 ms in /usr/share/php/openmediavault/system/process.inc:197
Stack trace:
#0 /usr/share/php/openmediavault/engine/module/serviceabstract.inc(62): OMV\System\Process->execute()
#1 /usr/share/openmediavault/engined/rpc/config.inc(170): OMV\Engine\Module\ServiceAbstract->deploy()
#2 [internal function]: Engined\Rpc\Config->applyChanges(Array, Array)
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#4 /usr/share/php/openmediavault/rpc/serviceabstract.inc(149): OMV\Rpc\ServiceAbstract->callMethod('applyChanges', Array, Array)
#5 /usr/share/php/openmediavault/rpc/serviceabstract.inc(588): OMV\Rpc\ServiceAbstract->OMV\Rpc\{closure}('/tmp/bgstatusSA...', '/tmp/bgoutput8O...')
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(159): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure))
#7 /usr/share/openmediavault/engined/rpc/config.inc(192): OMV\Rpc\ServiceAbstract->callMethodBg('applyChanges', Array, Array)
#8 [internal function]: Engined\Rpc\Config->applyChangesBg(Array, Array)
#9 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#10 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('applyChangesBg', Array, Array)
#11 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('Config', 'applyChangesBg', Array, Array, 1)
#12 {main}
```

**Comment by connected201** [comment]
also this error appear again when i do same action in [User Management](https://192.168.1.173/#/usermgmt) [Users](https://192.168.1.173/#/usermgmt/users) [Privileges](https://192.168.1.173/#/usermgmt/users/privileges/connected)

![](https://user-images.githubusercontent.com/20506433/160232551-30327186-0c5e-4b06-a339-47841ee3257a.png)

**Comment by votdev** [comment]
How can we reproduce this? What file systems do we need to create, shared folders, what services are using the shared folders. All that play into role to isolate the problem.

**Comment by connected201** [comment]
i can give access to my test environment, but i don't know how i can do it safety

**Comment by connected201** [comment]
it's proxmox image, i can upload .qcow file and give link to you (only if you use proxmox).

**Comment by maxkratz** [comment]
> it's proxmox image, i can upload .qcow file and give link to you (only if you use proxmox).

AFAIK are proxmox qcow files just normal KVM/QEMU image files. They can be booted wíthout proxmox :).

**Comment by ryecoaaron** [comment]
@maxkratz correct. I actually have used many with the kvm plugin without changing anything.

**Comment by TGTF** [comment]
I am also experiencing the same issue
