### ISSUE TITLE
omv-mkaptidx  error

### ISSUE THREAD

**Issue by WarlockFish** [openmediavault/openmediavault#1334]
**Please only open an issue here, when advised by a moderator in openmediavault forum.**

Requests for support and questions shall be addressed first to openmediavault forum: https://forum.openmediavault.org/

**Note:** Issues for non-core plugins are to be raised in the corresponding https://github.com/OpenMediaVault-Plugin-Developers repository

**Describe the bug**

```
................ buster InRelease [13.7 kB]
Fetched 93.4 kB in 6s (16.1 kB/s)     
Traceback (most recent call last):
  File "/usr/sbin/omv-mkaptidx", line 138, in <module>
    "package": pkg.candidate.record.get("Package"),
  File "/usr/lib/python3/dist-packages/apt/package.py", line 671, in record
    return Record(self._records.record)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 1627: invalid continuation byte
Reading package lists... Done

```

i use `apt-get update` ,get this messages.

**Expected behavior**

**Screenshots**

![图片](https://user-images.githubusercontent.com/30708115/176080906-bc1a7a15-f38c-47b1-81c4-34adef9b37f4.png)

**Reference to Forum**

**openmediavault Server (please complete the following information):**

- OS version: [uname -a]

```
Linux raspbian 5.10.60-Release-OPENFANS+20210824-v8 #1 SMP PREEMPT Tue Aug 24 01:44:01 CST 2021 aarch64 GNU/Linux
```
- openmediavault version: [dpkg -l | grep openmediavault]

```
dpkg -l | grep openmediavault 
rc  omvextras-unionbackend                 5.0.2                                 all          union filesystems backend plugin for openmediavault
ii  openmediavault                         6.0.30-1                              all          openmediavault - The open network attached storage solution
ii  openmediavault-anacron                 6.0.1                                 all          anacron plugin for OpenMediaVault.
ii  openmediavault-apttool                 6.0.1                                 all          apt tool plugin for OpenMediaVault.
ii  openmediavault-backup                  6.0.4                                 all          backup plugin for OpenMediaVault.
ii  openmediavault-borgbackup              6.1.3                                 all          borgbackup plugin for OpenMediaVault.
ii  openmediavault-clamav                  6.0-9                                 all          openmediavault ClamAV plugin
ii  openmediavault-compose                 6.0.1                                 all          OpenMediaVault compose plugin
ii  openmediavault-cputemp                 6.1.1                                 all          cpu temperature plugin for openmediavault
ii  openmediavault-diskstats               6.0-6                                 all          openmediavault disk monitoring plugin
ii  openmediavault-downloader              6.0.1                                 all          OpenMediaVault downloader plugin
ii  openmediavault-fail2ban                6.0.2                                 all          OpenMediaVault Fail2ban plugin
ii  openmediavault-filebrowser             6.0.1-1                               all          openmediavault File Browser plugin
ii  openmediavault-flashmemory             6.1                                   all          folder2ram plugin for openmediavault
ii  openmediavault-keyring                 1.0                                   all          GnuPG archive keys of the OpenMediaVault archive
ii  openmediavault-locate                  6.0                                   all          locate plugin for OpenMediaVault.
ii  openmediavault-luksencryption          6.0                                   all          OpenMediaVault LUKS encryption plugin
ii  openmediavault-lvm2                    6.0-8                                 all          openmediavault Logical Volume Manager (LVM2) plugin
ii  openmediavault-mergerfs                6.1.1                                 all          mergerfs plugin for openmediavault.
ii  openmediavault-minidlna                6.0.3                                 all          OpenMediaVault miniDLNA (DLNA server) plugin
ii  openmediavault-omvextrasorg            6.0.9                                 all          OMV-Extras.org Package Repositories for OpenMediaVault
ii  openmediavault-owntone                 6.0.2-2                               all          openmediavault OwnTone plugin
ii  openmediavault-photoprism              6.0.4-1                               all          openmediavault PhotoPrism plugin
ii  openmediavault-remotemount             6.0.1                                 all          Remote mount plugin for OpenMediaVault.
ii  openmediavault-resetperms              6.0                                   all          Reset Permissions
ii  openmediavault-sftp                    6.0                                   all          sftp server
ii  openmediavault-sharerootfs             6.0-4                                 all          openmediavault share root filesystem plugin
ii  openmediavault-snmp                    6.0-5                                 all          openmediavault SNMP (Simple Network Management Protocol) plugin
ii  openmediavault-symlinks                6.0.4                                 all          OpenMediaVault symlinks plugin
ii  openmediavault-tftp                    6.0-4                                 all          openmediavault TFTP-Server plugin
ii  openmediavault-tgt                     6.0.4                                 all          OpenMediaVault tgt plugin
ii  openmediavault-usbbackup               6.0-11                                all          openmediavault USB/eSATA backup plugin
```

- Device:  pi
- OS: shell 

.

**Comment by votdev** [comment]
This error may indicate that the package database is corrupted.

You may try to fix that by running
```
# rm -rf /var/lib/apt/lists/
# apt-get update
```
