### ISSUE TITLE
Python3 error on every apt update

### ISSUE THREAD

**Issue by ET-Bent** [openmediavault/openmediavault#138]
When running `apt update` `apt dist-upgrade` I always get these error lines in my log:

```bash
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f04c2377730>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f04c2377730>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
```

Is there any way to fix this?

**System:**
```
OMV 4.1.8.2-1 (Arrakis)
Linux 4.16.0-0.bpo.2-amd64 #1 SMP Debian 4.16.16-2~bpo9+1 (2018-06-26) x86_64 GNU/Linux
Debian 9.5 Stretch
```

**Comment by ryecoaaron** [comment]
https://forum.openmediavault.org/index.php/Thread/19658-Upgrade-Debian-9-and-4-x/?postID=155621#post155621

**Comment by alugowski** [comment]
This issue should be reopened. It occurs on a fresh install.

**Comment by votdev** [comment]
This is an upstream issue and must be fixed by the Python Debian package manager.
