### ISSUE TITLE
can't apply any change 

### ISSUE THREAD

**Issue by NOBB2333** [openmediavault/openmediavault#1439]
**Describe the bug**

i just can't make any change in port 80 GUI,

**To Reproduce**

1.install  system
2.docker install filebrowser/filebrowser
3.install OMV-extral plug-in
4.docker install mysql
5.change chinese inage source

after 5, start sometimes options can't apply 
then i find all the changes can't apply ,even add a user

**Expected behavior**

mabe is point 5 change some optons,but i change only is docker images,
should't be can't apply

**Screenshots**

**Reference to Forum**

- OS version: [uname -a]
- openmediavault version: [dpkg -l | grep openmediavault]

**Client (please complete the following information):**

- Device: cpu N3540
- OS: OMV 6.04
- Browser: fire fox
- Version 6.04

**Additional context**

is there have any way to change origin files to change GUI data?

thanks for read

**Comment by NOBB2333** [comment]
Screenshots:

![图片](https://user-images.githubusercontent.com/72846817/206976942-b80dd442-693e-4068-a4ee-f9f3ae4492bf.png)


` 500 - Internal Server Error
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; omv-salt deploy run --no-color monit 2>&1' with exit code '1': Traceback (most recent call last): File "/sbin/omv-salt", line 152, in <module> sys.exit(main()) File "/sbin/omv-salt", line 147, in main cli() File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1130, in __call__ return self.main(*args, **kwargs) File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1055, in main rv = self.invoke(ctx) File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1657, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1657, in invoke return _process_result(sub_ctx.command.invoke(sub_ctx)) File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in invoke return ctx.invoke(self.callback, **ctx.params) File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 760, in invoke return __callback(*args, **kwargs) File "/sbin/omv-salt", line 133, in deploy_run caller = salt.client.Caller(mopts=mopts) File "/usr/lib/python3/dist-packages/salt/client/__init__.py", line 2098, in __init__ import salt.minion File "/usr/lib/python3/dist-packages/salt/minion.py", line 36, in <module> import salt.pillar File "/usr/lib/python3/dist-packages/salt/pillar/__ini... `

**Comment by yves84** [comment]
Hi,

same problem if i use photoprism (6.0.7-1) plugin. Maybe Docker is a Ploblem?

OpenmediaVault 6.1.1-1 (Stable ISO)

**Comment by votdev** [comment]
Please post the complete output of `export LANG=C.UTF-8; export LANGUAGE=; omv-salt deploy run --no-color monit`.

**Comment by yves84** [comment]
```KeyError: 'saltutil.is_running'```

This error occurred when i removed a user. Next day. i could apply the changes. I do not know 100% how to reproduce the error. Last week the same error occurred when changing the setting from samba.
 
WebUI Error:
```
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; omv-salt deploy run --no-color postfix 2>&1' with exit code '1': Traceback (most recent call last):
  File "/sbin/omv-salt", line 152, in <module>
    sys.exit(main())
  File "/sbin/omv-salt", line 147, in main
    cli()
  File "/usr/lib/python3/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/sbin/omv-salt", line 134, in deploy_run
    result = caller.cmd("state.orchestrate", names)
  File "/usr/lib/python3/dist-packages/salt/client/__init__.py", line 2122, in cmd
    return self.sminion.functions[fun](*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1235, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2268, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2283, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/modules/state.py", line 354, in orchestrate
    return _orchestrate(
  File "/usr/lib/python3/dist-packages/salt/runners/state.py", line 116, in orchestrate
    running = minion.functions["state.sls"](
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1235, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2268, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2283, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/modules/state.py", line 1269, in sls
    conflict = running(concurrent)
  File "/usr/lib/python3/dist-packages/salt/modules/state.py", line 379, in running
    active = __salt__["saltutil.is_running"]("state.*")
  File "/usr/lib/python3/dist-packages/salt/loader_context.py", line 72, in __getitem__
    return self.value()[item]
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1403, in __getitem__
    func = super().__getitem__(item)
  File "/usr/lib/python3/dist-packages/salt/utils/lazy.py", line 108, in __getitem__
    raise KeyError(key)
KeyError: 'saltutil.is_running'

OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; omv-salt deploy run --no-color postfix 2>&1' with exit code '1': Traceback (most recent call last):
  File "/sbin/omv-salt", line 152, in <module>
    sys.exit(main())
  File "/sbin/omv-salt", line 147, in main
    cli()
  File "/usr/lib/python3/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/sbin/omv-salt", line 134, in deploy_run
    result = caller.cmd("state.orchestrate", names)
  File "/usr/lib/python3/dist-packages/salt/client/__init__.py", line 2122, in cmd
    return self.sminion.functions[fun](*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1235, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2268, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2283, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/modules/state.py", line 354, in orchestrate
    return _orchestrate(
  File "/usr/lib/python3/dist-packages/salt/runners/state.py", line 116, in orchestrate
    running = minion.functions["state.sls"](
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1235, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2268, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 2283, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/modules/state.py", line 1269, in sls
    conflict = running(concurrent)
  File "/usr/lib/python3/dist-packages/salt/modules/state.py", line 379, in running
    active = __salt__["saltutil.is_running"]("state.*")
  File "/usr/lib/python3/dist-packages/salt/loader_context.py", line 72, in __getitem__
    return self.value()[item]
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1403, in __getitem__
    func = super().__getitem__(item)
  File "/usr/lib/python3/dist-packages/salt/utils/lazy.py", line 108, in __getitem__
    raise KeyError(key)
KeyError: 'saltutil.is_running' in /usr/share/php/openmediavault/system/process.inc:217
Stack trace:
#0 /usr/share/php/openmediavault/engine/module/serviceabstract.inc(62): OMV\System\Process->execute()
#1 /usr/share/openmediavault/engined/rpc/config.inc(170): OMV\Engine\Module\ServiceAbstract->deploy()
#2 [internal function]: Engined\Rpc\Config->applyChanges(Array, Array)
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#4 /usr/share/php/openmediavault/rpc/serviceabstract.inc(149): OMV\Rpc\ServiceAbstract->callMethod('applyChanges', Array, Array)
#5 /usr/share/php/openmediavault/rpc/serviceabstract.inc(619): OMV\Rpc\ServiceAbstract->OMV\Rpc\{closure}('/tmp/bgstatusLj...', '/tmp/bgoutputru...')
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(159): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure))
#7 /usr/share/openmediavault/engined/rpc/config.inc(192): OMV\Rpc\ServiceAbstract->callMethodBg('applyChanges', Array, Array)
#8 [internal function]: Engined\Rpc\Config->applyChangesBg(Array, Array)
#9 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#10 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('applyChangesBg', Array, Array)
#11 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('Config', 'applyChangesBg', Array, Array, 1)
#12 {main}
```

```
root@pinas:~# export LANG=C.UTF-8; export LANGUAGE=; omv-salt deploy run --no-color monit
piNas:
----------
          ID: remove_monit_collectd_service
    Function: file.absent
        Name: /etc/monit/conf.d/openmediavault-collectd.conf
      Result: True
     Comment: File /etc/monit/conf.d/openmediavault-collectd.conf is not present
     Started: 09:13:49.752365
    Duration: 5.327 ms
     Changes:   
----------
          ID: configure_monit_filesystem_service
    Function: file.managed
        Name: /etc/monit/conf.d/openmediavault-filesystem.conf
      Result: True
     Comment: File /etc/monit/conf.d/openmediavault-filesystem.conf is in the correct state
     Started: 09:13:49.758450
    Duration: 244.786 ms
     Changes:   
----------
          ID: configure_monit_nginx_service
    Function: file.managed
        Name: /etc/monit/conf.d/openmediavault-nginx.conf
      Result: True
     Comment: File /etc/monit/conf.d/openmediavault-nginx.conf is in the correct state
     Started: 09:13:50.003898
    Duration: 70.466 ms
     Changes:   
----------
          ID: configure_monit_omv-engined_service
    Function: file.managed
        Name: /etc/monit/conf.d/openmediavault-engined.conf
      Result: True
     Comment: File /etc/monit/conf.d/openmediavault-engined.conf is in the correct state
     Started: 09:13:50.075031
    Duration: 54.697 ms
     Changes:   
----------
          ID: configure_monit_php-fpm_service
    Function: file.managed
        Name: /etc/monit/conf.d/openmediavault-phpfpm.conf
      Result: True
     Comment: File /etc/monit/conf.d/openmediavault-phpfpm.conf is in the correct state
     Started: 09:13:50.130399
    Duration: 56.659 ms
     Changes:   
----------
          ID: remove_monit_proftpd_service
    Function: file.absent
        Name: /etc/monit/conf.d/openmediavault-proftpd.conf
      Result: True
     Comment: File /etc/monit/conf.d/openmediavault-proftpd.conf is not present
     Started: 09:13:50.187856
    Duration: 3.801 ms
     Changes:   
----------
          ID: remove_monit_rrdcached_service
    Function: file.absent
        Name: /etc/monit/conf.d/openmediavault-rrdcached.conf
      Result: True
     Comment: File /etc/monit/conf.d/openmediavault-rrdcached.conf is not present
     Started: 09:13:50.192326
    Duration: 3.425 ms
     Changes:   
----------
          ID: configure_monit_system_service
    Function: file.managed
        Name: /etc/monit/conf.d/openmediavault-system.conf
      Result: True
     Comment: File /etc/monit/conf.d/openmediavault-system.conf is in the correct state
     Started: 09:13:50.196446
    Duration: 120.514 ms
     Changes:   
----------
          ID: configure_default_monit
    Function: file.managed
        Name: /etc/default/monit
      Result: True
     Comment: File /etc/default/monit is in the correct state
     Started: 09:13:50.317708
    Duration: 14.494 ms
     Changes:   
----------
          ID: divert_default_monit
    Function: omv_dpkg.divert_add
        Name: /etc/default/monit
      Result: True
     Comment: Leaving 'local diversion of /etc/default/monit to /etc/default/monit.distrib'
     Started: 09:13:50.336518
    Duration: 70.463 ms
     Changes:   
----------
          ID: configure_monit_monitrc
    Function: file.managed
        Name: /etc/monit/monitrc
      Result: True
     Comment: File /etc/monit/monitrc is in the correct state
     Started: 09:13:50.407950
    Duration: 124.701 ms
     Changes:   
----------
          ID: divert_monit_monitrc
    Function: omv_dpkg.divert_add
        Name: /etc/monit/monitrc
      Result: True
     Comment: Leaving 'local diversion of /etc/monit/monitrc to /etc/monit/monitrc.distrib'
     Started: 09:13:50.533330
    Duration: 60.851 ms
     Changes:   
----------
          ID: test_monit_config
    Function: cmd.run
        Name: monit -t
      Result: True
     Comment: Command "monit -t" run
     Started: 09:13:50.599925
    Duration: 71.932 ms
     Changes:   
              ----------
              pid:
                  3909
              retcode:
                  0
              stderr:
              stdout:
                  Control file syntax OK
----------
          ID: reload_monit_service
    Function: service.running
        Name: monit
      Result: True
     Comment: The service monit is already running
     Started: 09:13:50.770373
    Duration: 169.903 ms
     Changes:   

Summary for piNas
-------------
Succeeded: 14 (changed=1)
Failed:     0
-------------
Total states run:     14
Total run time:    1.072 s
```
