### ISSUE TITLE
Webapp shows disks that never have been mounted

### ISSUE THREAD

**Issue by hgschwibbe** [openmediavault/openmediavault#1464]
**Describe the bug**

I am currently running a rsync backup from `/dev/sda1` to another `/dev/sdb1`. 
After refreshing the browser to get rid of the background task dialog I faced some strange display on my Dashboard.
The device `/dev/sda1` was gone and has been replaced by  `/dev/scd1`  which is shown as not mounted.

Then I switched to the Disks where I recognized that one of my disks have been mounted to some other device.

So I connected to my machine via SSH and entered the command  `df -lha` where the mount points were shown correctly.

**Screenshots**

![Dashboard](https://user-images.githubusercontent.com/1725648/211419952-00351a4a-e524-4333-a5c3-b6fe7875b7fd.png)
![df](https://user-images.githubusercontent.com/1725648/211419960-5a3b4599-5e6c-4eff-acb4-d76d60e1eb8c.png)
![Disks](https://user-images.githubusercontent.com/1725648/211419963-e18d6f04-9993-4d93-ab57-567dc4adc028.png)
URL link to forum post

**openmediavault Server (please complete the following information):**

- OS version:
Linux 5.15.84-v7l+ #1613 SMP Thu Jan 5 12:01:26 GMT 2023 armv7l GNU/Linux

- openmediavault version:
ii  openmediavault                       6.1.4-2                          all          openmediavault - The open network attached storage solution
ii  openmediavault-clamav                6.0.2-1                          all          openmediavault ClamAV plugin
ii  openmediavault-fail2ban              6.0.3                            all          OpenMediaVault Fail2ban plugin
ii  openmediavault-flashmemory           6.2                              all          folder2ram plugin for openmediavault
ii  openmediavault-keyring               1.0                              all          GnuPG archive keys of the OpenMediaVault archive
ii  openmediavault-omvextrasorg          6.1.1                            all          OMV-Extras.org Package Repositories for OpenMediaVault

**Client (please complete the following information):**

- Device: Raspberry Pi 4 with two Samsung T7 SSD via USB 3.0
- OS: Raspbian
- Browser Firefox 108.0.2 (64-Bit)

**Comment by hgschwibbe** [comment]
Another try when I plug/unplug both SSDs into the same USB port a couple of times:
![grafik](https://user-images.githubusercontent.com/1725648/211423578-7368f450-e026-4846-8a8e-603fda92ed59.png)

**Comment by votdev** [comment]
All your problems sounds like a malfunctioning USB hub which forwards the same UUID for every connected device. In this case OMV does not work because it is using predictable device names which consists of the unique device identifier. In your case there are several devices with the same identifier which breaks OMV. A second problem appears which is that the kernel assigns device names like /dev/sdX according to which he sees at first. Timing issues will now shuffle the device names on each reboot. That's why predictable device names are required by OMV.

Please consider using right hardware, a RasPi is not made for a NAS. This is my personal opinion.

**Comment by votdev** [comment]
Please post the output of the following CLI commands (run as root):
```
# blkid
# omv-confdbadm read --prettify conf.system.filesystem.mountpoint
```

**Comment by votdev** [comment]
> Result is that /dev/sdb1 is shown Online, but df shows /dev/sda1 has been mounted only.

After checking the screenshots again... may it be possible that both filesystems have the same UUID? this can be the reason why sometimes one and then the other file system is mounted.

But we will see when you provide the above mentioned information. Please run the commands with all devices plugged in.

**Comment by hgschwibbe** [comment]
The general concept of UUID generation is that you never generate a UUID twice.
And I think a company like Samsung will not sell SSDs with duplicate UUIDs.

The output of `blkid` also shows that there are no duplicated UUIDs:
```
/dev/mmcblk0p1: LABEL_FATBOOT="boot" LABEL="boot" UUID="AE82-4BC1" BLOCK_SIZE="512" TYPE="vfat" PARTUUID="b4ce1f96-01"
/dev/mmcblk0p2: LABEL="rootfs" UUID="6d2ff93e-eacd-415c-96d5-4611ad21e05f" BLOCK_SIZE="4096" TYPE="ext4" PARTUUID="b4ce1f96-02"
/dev/sda1: LABEL="SHARE" UUID="e4a5067b-3a47-450a-9ccf-a1371a52a664" BLOCK_SIZE="4096" TYPE="ext4" PARTUUID="eee41f58-01"
/dev/sdb1: LABEL="BACKUP" UUID="47c85df0-605d-4f89-ad9e-6e2c0ad22eb4" BLOCK_SIZE="4096" TYPE="ext4" PARTUUID="fa352724-01"
```

But the output of  `omv-confdbadm read --prettify conf.system.filesystem.mountpoint` looks like a stacktrace:

```
Traceback (most recent call last):
  File "/usr/sbin/omv-confdbadm", line 76, in <module>
    sys.exit(main())
  File "/usr/sbin/omv-confdbadm", line 72, in main
    return cmd_inst.execute(*sys.argv)
  File "/usr/share/openmediavault/confdbadm/commands.d/read.py", line 73, in execute
    objs = db.get(cmd_args.id, cmd_args.uuid)
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 85, in get
    query.execute()
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 734, in execute
    elements = self._execute_xpath()
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 416, in _execute_xpath
    root_element = self._get_root_element()
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 407, in _get_root_element
    self._load()
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 386, in _load
    self._root_element = lxml.etree.parse(self._database_file)
  File "src/lxml/etree.pyx", line 3521, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1859, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1885, in lxml.etree._parseDocumentFromURL
  File "src/lxml/parser.pxi", line 1789, in lxml.etree._parseDocFromFile
  File "src/lxml/parser.pxi", line 1177, in lxml.etree._BaseParser._parseDocFromFile
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 652, in lxml.etree._raiseParseError
OSError: Error reading file '/etc/openmediavault/config.xml': failed to load external entity "/etc/openmediavault/config.xml"

```
The specified file is there, but its empty, is this correct?

**Comment by hgschwibbe** [comment]
Another think I am asking me is: 
OMV mounts UUIDs to file system directories
Why do we have a Disk page in the webapp which shows `/dev` directories instead of UUIDs?
This is confusing me when I try to link the information of `/etc/fstab` with the Disk page in my mind:

```
# >>> [openmediavault]
/dev/disk/by-uuid/e4a5067b-3a47-450a-9ccf-a1371a52a664		/srv/dev-disk-by-uuid-e4a5067b-3a47-450a-9ccf-a1371a52a664	ext4	defaults,nofail,user_xattr,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl	0 2
/dev/disk/by-uuid/47c85df0-605d-4f89-ad9e-6e2c0ad22eb4		/srv/dev-disk-by-uuid-47c85df0-605d-4f89-ad9e-6e2c0ad22eb4	ext4	defaults,nofail,user_xattr,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl	0 2
# <<< [openmediavault]
```

**Comment by votdev** [comment]
> And I think a company like Samsung will not sell SSDs with duplicate UUIDs.

According to users and the investigations we did this has happened; maybe not Samsung.

**Comment by votdev** [comment]
> The specified file is there, but its empty, is this correct?

No, your installation is completely broken. Maybe there is a backup available to recover. What is the output of `ls -alh /etc/openmediavault`?

**Comment by votdev** [comment]
> Why do we have a Disk page in the webapp which shows /dev directories instead of UUIDs?

Because unpredictable device names are easier to handle. I don't think you as a user want to see long device names that nobody can remember. When you work in the UI, it is better to work with /dev/sdX device names; the backend will work with the predictable ones.

**Comment by votdev** [comment]
> This is confusing me when I try to link the information from /etc/fstab with the Disk page in my mind:

This is what OMV is designed for; you should not take care about what happens under the hood.

**Comment by votdev** [comment]
> Probably OMV will become more stable against reconnecting SSDs with different /dev mapping.

OMV is already rock stable. As mentioned above, predictable devices names are already used system wide under the hood, but these device names are not published to the user to make it easrier to work with. If you create a RAID for example, it is easier to select the devices that are names /dev/sd1, /dev/sd2 instead of the unreadable /dev/disk/by-uuid/e4a5067b-3a47-450a-9ccf-a1371a52a664 and /dev/disk/by-uuid/47c85df0-605d-4f89-ad9e-6e2c0ad22eb4.

I don't know what happens on your system right now, but this seems to be an edge case or a user generated problem.

**Comment by votdev** [comment]
> Another try when I plug/unplug both SSDs into the same USB port a couple of times: ![grafik](https://user-images.githubusercontent.com/1725648/211423578-7368f450-e026-4846-8a8e-603fda92ed59.png) Result is that `/dev/sdb1` is shown Online, but df shows `/dev/sda1` has been mounted only.

This seems to be caused because your database is broken as we have seen above: `Error reading file '/etc/openmediavault/config.xml': failed to load external entity "/etc/openmediavault/config.xml"`; no data from the database + live information can be merged and displayed in the UI.

Please reinstall your system or make sure a backup of the `/etc/openmediavault/config.xml` file is recovered. Make sure that you never switch off the SBC device without shut it down properly. Switching off a SBC is the most reason for loosing data. Based on user feedback this mostly happens to Raspi and other ARM based SBCs. Another reason is faulty and too weak power supply of the devices.

**Comment by votdev** [comment]
> Is it relevant for OMV when the Kernel is unable to remember UUID/dev mappings?

The kernel does not need to remember. UDEV is using the serial number of the harddisk to generate the predictable device name. This is a problem if you are using crappy USB hubs with chipsets that do not forward the REAL serial number of the SSH/harddisk, instead faking it and forwarding them for ALL connected devices. That's another reason why SBCs are not really mad for a NAS, a x64 board with real SATA ports will not have all that troubles.

**Comment by hgschwibbe** [comment]
> > The specified file is there, but its empty, is this correct?
> 
> No, your installation is completely broken. Maybe there is a backup available to recover. What is the output of `ls -alh /etc/openmediavault`?

ok I had do execute `sudo omv-confdbadm read --prettify conf.system.filesystem.mountpoint`. 
When I make `sudo`, I will get can read the `config.xml` and its not empty.

```
pi@hotelgolfsierra:~ $ sudo omv-confdbadm read --prettify conf.system.filesystem.mountpoint
[
    {
        "comment": "SHARE",
        "dir": "/srv/dev-disk-by-uuid-e4a5067b-3a47-450a-9ccf-a1371a52a664",
        "freq": 0,
        "fsname": "/dev/disk/by-uuid/e4a5067b-3a47-450a-9ccf-a1371a52a664",
        "hidden": false,
        "opts": "defaults,nofail,user_xattr,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl",
        "passno": 2,
        "type": "ext4",
        "usagewarnthreshold": 85,
        "uuid": "bfdb98ed-8010-4532-bca9-fc7f80c20c07"
    },
    {
        "comment": "BACKUP",
        "dir": "/srv/dev-disk-by-uuid-47c85df0-605d-4f89-ad9e-6e2c0ad22eb4",
        "freq": 0,
        "fsname": "/dev/disk/by-uuid/47c85df0-605d-4f89-ad9e-6e2c0ad22eb4",
        "hidden": false,
        "opts": "defaults,nofail,user_xattr,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl",
        "passno": 2,
        "type": "ext4",
        "usagewarnthreshold": 85,
        "uuid": "42c98eb5-0ca9-44cf-b63b-4d3140a2c58f"
    }
]
```

So it looks my installation is not broken :-)

I know you don't like the Raspberry Pi, but please focus  the facts.

Currently I don't have an indicator that my Raspberry Pi's USB controller fakes some UUIDs. When I mount the SSDs on my Dell Notebook GParted shows me the same UUIDs as configured in the Rasperry Pi.
![GParted](https://user-images.githubusercontent.com/1725648/211618032-49f3b34b-7ab3-4c42-b87a-38da8b36246d.png)

According to the weak power supply you are 100% right. I have an external USB Hub with a power supply now and everything seems to work from now on.

**Comment by hgschwibbe** [comment]
> > Why do we have a Disk page in the webapp which shows /dev directories instead of UUIDs?
> 
> Because unpredictable device names are easier to handle. I don't think you as a user want to see long device names that nobody can remember. When you work in the UI, it is better to work with /dev/sdX device names; the backend will work with the predictable ones.

Its not a story about what the user like to see, the webapp should identify the disk by a unique identifier like the UUID.
Only a unique identifier guarantees that the disk will be identified again after it has been unplugged.
And the /dev device is not a good identifier because it may change.

**Comment by hgschwibbe** [comment]
> What is the output of `mount`?

```
/dev/sda1 on /srv/dev-disk-by-uuid-e4a5067b-3a47-450a-9ccf-a1371a52a664 type ext4 (rw,relatime,stripe=8191,jqfmt=vfsv0,usrjquota=aquota.user,grpjquota=aquota.group)
/dev/sdb1 on /srv/dev-disk-by-uuid-47c85df0-605d-4f89-ad9e-6e2c0ad22eb4 type ext4 (rw,relatime,stripe=8191,jqfmt=vfsv0,usrjquota=aquota.user,grpjquota=aquota.group)
```

**Comment by hgschwibbe** [comment]
What about working with a unique name that has to be given when the user creates a disk?
And this unique name will be shown instead of the confusing and changing /dev device.
Under the hood the unique name is connected to the UUID and a helper function just makes the resolution
`getUuidByUniqueName(String uniqueDiskName)`

**Comment by votdev** [comment]
> > > Why do we have a Disk page in the webapp which shows /dev directories instead of UUIDs?
> > 
> > 
> > Because unpredictable device names are easier to handle. I don't think you as a user want to see long device names that nobody can remember. When you work in the UI, it is better to work with /dev/sdX device names; the backend will work with the predictable ones.
> 
> Its not a story about what the user like to see, the webapp should identify the disk by a unique identifier like the UUID. Only a unique identifier guarantees that the disk will be identified again after it has been unplugged. And the /dev device is not a good identifier because it may change.

Sorry, it seems you want to explain me how to do it? Please become familiar with Linux, the kernel and especially UDEV before you give smart tips. Everything you are suggesting is done by OMV already.

**Comment by votdev** [comment]
> Only a unique identifier guarantees that the disk will be identified again after it has been unplugged.

Pulling main storage devices out of a NAS to share it with another operating system is not the way to proceed with a NAS. For this purpose the `openmediavault-usbbackup` plugin exists which is used to import/export huge data.

**Comment by votdev** [comment]
> After refreshing the browser to get rid of the background task dialog I faced some strange display on my Dashboard.

To say it in the word of Steve Jobs: You are using it wrong. 

The modal dialog is used to prevent the user from doing bad things and ensure that the UI is not displaying incorrect/temporary useless data. Don't wonder about `strange display on my Dashboard` if you are doing that.

**Comment by votdev** [comment]
I'm stopping my research here because I really don't know what you're doing with the system and it's too much of a waste of my time.

**Comment by hgschwibbe** [comment]
There is not so much I am doing with the system.
I have only two rsync tasks, one pulls a Windows Backup from a remote Windows Server.
And the other rsync task copies the backup to another SSD.

![grafik](https://user-images.githubusercontent.com/1725648/211657609-e22d2dba-4928-4f0b-9c02-ac4512608efc.png)

With the USB plug and play issue I just wanna show up a problem when the kernel assigns a disk to another /dev folder.
But sorry for my ten cents and wasting your time.

**Comment by TheMelmacian** [comment]
> Another think I am asking me is:
> OMV mounts disks by UUIDs.
> Why do we have a Disk page in the webapp which shows `/dev` directories instead of UUIDs?
> This is confusing me when I try to link the information from `/etc/fstab` with the Disk page in my mind:

With _Show/Hide columns_ in the right top corner of the tables in the _Disk_ and _File System_ overviews you can add additional columns which include device symlinks for disks and mountpoints (dev-disk-by-uuid...) for file systems.
So the webapp provides the information you ask, but it is hidden by default.

**Comment by hgschwibbe** [comment]
And how do you apply that to the dashboard?

When I ran an rsync task "/dev/sdb1" became "/dev/sdc1".
That was the main reason why I opened this ticket.

But the developer blames my hardware and refuses further investigation.

There is nothing you can do.
