### ISSUE TITLE
omv7: openmediavault-md: getting 500 when trying to apply mdadm chaneges

### ISSUE THREAD

**Issue by mina86** [openmediavault/openmediavault#1665]
After installing mdadm plugin and adding a RAID1 device updates through the web UI stopped working.  Specifically, I’m now getting a 500 error whenever I try to apply the pending configuration changes.

While I got mdadm working just fine through SSH, the failure stops me from applying any further changes.

The error message mentioned running omv-salt so I’ve tried that through SSH and got the following:

```
~# ( export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; omv-salt deploy run --no-color mdadm )
debian:
    Data failed to compile:
----------
    Rendering SLS 'base:omv.deploy.mdadm.20mdadm' failed: Jinja error: Object of type StrictUndefined is not JSON serializable
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 477, in render_jinja_tmpl
    output = template.render(**decoded_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 43, in top-level template code
  File "/usr/lib/python3/dist-packages/salt/utils/jinja.py", line 1003, in format_json
    json_txt = salt.utils.json.dumps(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/salt/utils/json.py", line 170, in dumps
    return json_module.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type StrictUndefined is not JSON serializable

; line 43

---
[...]
    - source:
      - salt://{{ tpldir }}/files/etc-mdadm-mdadm.conf.j2
    - template: jinja
    - context:
        email_config: {{ email_config | json }}
        notification_config: {{ notification_config | json }}    <======================
    - user: root
    - group: root
    - mode: 644

mdadm_save_config:
[...]
---
[ERROR   ] Rendering exception occurred
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 477, in render_jinja_tmpl
    output = template.render(**decoded_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 43, in top-level template code
  File "/usr/lib/python3/dist-packages/salt/utils/jinja.py", line 1003, in format_json
    json_txt = salt.utils.json.dumps(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/salt/utils/json.py", line 170, in dumps
    return json_module.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type StrictUndefined is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 219, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 523, in render_jinja_tmpl
    raise SaltRenderError(
salt.exceptions.SaltRenderError: Jinja error: Object of type StrictUndefined is not JSON serializable
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 477, in render_jinja_tmpl
    output = template.render(**decoded_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 43, in top-level template code
  File "/usr/lib/python3/dist-packages/salt/utils/jinja.py", line 1003, in format_json
    json_txt = salt.utils.json.dumps(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/salt/utils/json.py", line 170, in dumps
    return json_module.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type StrictUndefined is not JSON serializable

; line 43

---
[...]
    - source:
      - salt://{{ tpldir }}/files/etc-mdadm-mdadm.conf.j2
    - template: jinja
    - context:
        email_config: {{ email_config | json }}
        notification_config: {{ notification_config | json }}    <======================
    - user: root
    - group: root
    - mode: 644

mdadm_save_config:
[...]
---
[CRITICAL] Rendering SLS 'base:omv.deploy.mdadm.20mdadm' failed: Jinja error: Object of type StrictUndefined is not JSON serializable
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 477, in render_jinja_tmpl
    output = template.render(**decoded_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 43, in top-level template code
  File "/usr/lib/python3/dist-packages/salt/utils/jinja.py", line 1003, in format_json
    json_txt = salt.utils.json.dumps(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/salt/utils/json.py", line 170, in dumps
    return json_module.dumps(obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type StrictUndefined is not JSON serializable

; line 43

---
[...]
    - source:
      - salt://{{ tpldir }}/files/etc-mdadm-mdadm.conf.j2
    - template: jinja
    - context:
        email_config: {{ email_config | json }}
        notification_config: {{ notification_config | json }}    <======================
    - user: root
    - group: root
    - mode: 644

mdadm_save_config:
[...]
---
```

**openmediavault Server (please complete the following information):**

- OS version: Linux shuno 6.1.0-16-amd64 \#1 SMP PREEMPT_DYNAMIC Debian 6.1.67-1 (2023-12-12) x86_64 GNU/Linux
- openmediavault version:
  - openmediavault                  7.0-18
  - openmediavault-compose          7.0.1
  - openmediavault-keyring          1.0.2-2
  - openmediavault-luksencryption   7.0.1
  - openmediavault-lvm2             7.0-1
  - openmediavault-md               7.0-4
  - openmediavault-omvextrasorg     7.0
  - openmediavault-owntone          7.0-1
  - openmediavault-rsnapshot        7.0
  - openmediavault-sharerootfs      7.0-1

**Comment by mina86** [comment]
In desperation I’ve edited /srv/salt/omv/deploy/mdadm/20mdadm.sls to read `notification_config: {}` and things worked and as far as I can tell the only difference is that MAILADDR and MAILFROM is not set.

One thing worth mentioning is that I did not have Notifications configured.  I have them set since but even when I set them applying changes failed.  However, this could be because the UI first tried to apply mdadm changes which failed.

**Comment by kinglionsoft** [comment]
Same error. The failure stops me from applying any further changes.

* openmediavault version:
   - openmediavault 7.1.1-1 (Sandworm)
   - openmediavault-md 7.0-7
   - openmediavault-hosts 7.0-3
   - openmediavault-lvm2 7.0-2
   - openmediavault-usbbackup 7.0.2-1

**Comment by votdev** [comment]
Run the following command which is normally executed during the package installation. Seems i failed on your systems:
```
# omv-confdbadm read --defaults "conf.system.notification.notification" | jq ".id = \"mdadm\"" | omv-confdbadm update "conf.system.notification.notification" -
```

**Comment by kinglionsoft** [comment]
thanks
