### ISSUE TITLE
installing on a arm64 octicore

### ISSUE THREAD

**Issue by N4CNR** [openmediavault/openmediavault#1829]
installing from the debian openmediavault pkgs on arm64 octicore has issues.
Setting up openmediavault (7.4.9-1) ...
Creating users/groups ...
Updating local package archive ...
Updating service units ...
systemd-journald.service is a disabled or a static unit, not starting it.
Creating configuration database ...
Setting up Salt environment ...
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 33, in <module>
    sys.exit(load_entry_point('salt==3007.0', 'console_scripts', 'salt-call')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/salt/scripts.py", line 438, in salt_call
    import salt.cli.call
  File "/usr/lib/python3/dist-packages/salt/cli/call.py", line 3, in <module>
    import salt.cli.caller
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 12, in <module>
    import salt.channel.client
  File "/usr/lib/python3/dist-packages/salt/channel/client.py", line 13, in <module>
    import salt.crypt
  File "/usr/lib/python3/dist-packages/salt/crypt.py", line 26, in <module>
    import salt.payload
  File "/usr/lib/python3/dist-packages/salt/payload.py", line 12, in <module>
    import salt.loader.context
  File "/usr/lib/python3/dist-packages/salt/loader/__init__.py", line 24, in <module>
    import salt.utils.event
  File "/usr/lib/python3/dist-packages/salt/utils/event.py", line 67, in <module>
    import salt.ext.tornado.iostream
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/iostream.py", line 41, in <module>
    from salt.ext.tornado.netutil import ssl_wrap_socket, ssl_match_hostname, SSLCertificateError, _client_ssl_defaults, _server_ssl_defaults
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/netutil.py", line 57, in <module>
    import backports.ssl_match_hostname
ModuleNotFoundError: No module named 'backports'
[ERROR   ] An un-handled exception was caught by Salt's global exception handler:
ModuleNotFoundError: No module named 'backports'
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 33, in <module>
    sys.exit(load_entry_point('salt==3007.0', 'console_scripts', 'salt-call')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/salt/scripts.py", line 438, in salt_call
    import salt.cli.call
  File "/usr/lib/python3/dist-packages/salt/cli/call.py", line 3, in <module>
    import salt.cli.caller
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 12, in <module>
    import salt.channel.client
  File "/usr/lib/python3/dist-packages/salt/channel/client.py", line 13, in <module>
    import salt.crypt
  File "/usr/lib/python3/dist-packages/salt/crypt.py", line 26, in <module>
    import salt.payload
  File "/usr/lib/python3/dist-packages/salt/payload.py", line 12, in <module>
    import salt.loader.context
  File "/usr/lib/python3/dist-packages/salt/loader/__init__.py", line 24, in <module>
    import salt.utils.event
  File "/usr/lib/python3/dist-packages/salt/utils/event.py", line 67, in <module>
    import salt.ext.tornado.iostream
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/iostream.py", line 41, in <module>
    from salt.ext.tornado.netutil import ssl_wrap_socket, ssl_match_hostname, SSLCertificateError, _client_ssl_defaults, _server_ssl_defaults
  File "/usr/lib/python3/dist-packages/salt/ext/tornado/netutil.py", line 57, in <module>
    import backports.ssl_match_hostname
ModuleNotFoundError: No module named 'backports'
dpkg: error processing package openmediavault (--configure):
 installed openmediavault package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 openmediavault

**Comment by votdev** [comment]
The problem surely comes from the Debian derivate you are using which is shipping newer Debian packages of several Python modules that do not match the versions required by the Salt package. With the Debian Bookworm repository (AMD64) i do not see any problems.

**Comment by votdev** [comment]
Alternatively you are using a backports repository which is not supported by OMV because it might cause to problems like those you are currently running into.

**Comment by ryecoaaron** [comment]
There are no python3 packages in backports.  I would be curious what the output of the following looks like:

dpkg -l | grep python3

**Comment by N4CNR** [comment]
ii  libpython3-stdlib:arm64                    3.12.6-1                             arm64        interactive high-level object-oriented language (default python3 version)
rc  libpython3.11-minimal:arm64                3.11.2-6+deb12u2                     arm64        Minimal subset of the Python language (version 3.11)
ii  libpython3.12-minimal:arm64                3.12.6-1                             arm64        Minimal subset of the Python language (version 3.12)
ii  libpython3.12-stdlib:arm64                 3.12.6-1                             arm64        Interactive high-level object-oriented language (standard library, version 3.12)
ii  libpython3.12t64:arm64                     3.12.6-1                             arm64        Shared Python runtime library (version 3.12)
ii  python3                                    3.12.6-1                             arm64        interactive high-level object-oriented language (default python3 version)
ii  python3-apt                                2.9.0+b1                             arm64        Python 3 interface to libapt-pkg
ii  python3-autocommand                        2.2.2-3                              all          library to generate argparse parsers from function signatures
ii  python3-bcrypt                             4.2.0-1                              arm64        password hashing library for Python 3
ii  python3-blinker                            1.8.2-1                              all          Fast, simple object-to-object and broadcast signaling (Python3)
ii  python3-brlapi:arm64                       6.6-5+b1                             arm64        Braille display access via BRLTTY - Python3 bindings
ii  python3-cached-property                    1.5.2-1                              all          Provides cached-property for decorating methods in classes (Python 3)
ii  python3-cairo                              1.26.1-2                             arm64        Python3 bindings for the Cairo vector graphics library
ii  python3-certifi                            2024.8.30-1                          all          root certificates for validating SSL certs and verifying TLS hosts (python3)
ii  python3-cffi-backend:arm64                 1.17.1-1                             arm64        Foreign Function Interface for Python 3 calling C code - runtime
ii  python3-chardet                            5.2.0+dfsg-1                         all          Universal Character Encoding Detector (Python3)
ii  python3-charset-normalizer                 3.3.2-4                              arm64        charset, encoding and language detection (Python 3)
ii  python3-click                              8.1.7-2                              all          Command-Line Interface Creation Kit - Python 3.x
ii  python3-colorama                           0.4.6-4                              all          Cross-platform colored terminal text in Python - Python 3.x
ii  python3-configobj                          5.0.9-1                              all          simple but powerful config file reader and writer for Python 3
ii  python3-cryptography                       43.0.0-1                             arm64        Python library exposing cryptographic recipes and primitives (Python 3)
ii  python3-cups:arm64                         2.0.4-1+b1                           arm64        Python3 bindings for CUPS
ii  python3-cupshelpers                        1.5.18-3                             all          Python utility modules around the CUPS printing system
ii  python3-dateutil                           2.9.0-3                              all          powerful extensions to the standard Python 3 datetime module
ii  python3-dbus                               1.3.2-5+b3                           arm64        simple interprocess messaging system (Python 3 interface)
ii  python3-debconf                            1.5.87                               all          interact with debconf from Python 3
ii  python3-debian                             0.1.49                               all          Python 3 modules to work with Debian-related data formats
ii  python3-dialog                             3.5.1-5                              all          Python module for making simple terminal-based user interfaces
ii  python3-distro                             1.9.0-1                              all          Linux OS platform information API
ii  python3-distro-info                        1.9                                  all          information about distributions' releases (Python 3 module)
ii  python3-freetype                           2.5.1-1                              all          Freetype Python bindings for Python 3
ii  python3-gi                                 3.48.2-1+b1                          arm64        Python 3 bindings for gobject-introspection libraries
ii  python3-gi-cairo                           3.48.2-1+b1                          arm64        Python 3 Cairo bindings for the GObject library
ii  python3-gnupg                              0.5.2-2                              all          Python wrapper for the GNU Privacy Guard (Python 3.x)
ii  python3-httplib2                           0.22.0-1                             all          comprehensive HTTP client library written for Python3
ii  python3-idna                               3.8-2                                all          Python IDNA2008 (RFC 5891) handling (Python 3)
ii  python3-inflect                            7.3.1-2                              all          Generate plurals, singular nouns, ordinals, indefinite articles (Python 3)
ii  python3-jaraco.context                     6.0.0-1                              all          jaraco contextlib extensions
ii  python3-jaraco.functools                   4.1.0-1                              all          additional functools in the spirit of stdlib's functools
ii  python3-jinja2                             3.1.3-1                              all          small but fast and easy to use stand-alone template engine
ii  python3-jmespath                           1.0.1-1                              all          JSON Matching Expressions (Python 3)
ii  python3-jwt                                2.7.0-1                              all          Python 3 implementation of JSON Web Token
ii  python3-lazr.restfulclient                 0.14.6-2                             all          client for lazr.restful-based web services (Python 3)
ii  python3-lazr.uri                           1.0.6-4                              all          library for parsing, manipulating, and generating URIs
ii  python3-looseversion                       1.3.0-3                              all          Version numbering for anarchists and software realists
ii  python3-louis                              3.31.0-2                             all          Python bindings for liblouis
ii  python3-lxml:arm64                         5.3.0-1                              arm64        pythonic binding for the libxml2 and libxslt libraries
ii  python3-markdown-it                        3.0.0-2                              all          Python port of markdown-it and some its associated plugins
ii  python3-markupsafe                         2.1.5-1+b1                           arm64        HTML/XHTML/XML string library
ii  python3-mdurl                              0.1.2-1                              all          Python port of the JavaScript mdurl package
ii  python3-minimal                            3.12.6-1                             arm64        minimal subset of the Python language (default python3 version)
ii  python3-more-itertools                     10.5.0-1                             all          library with routines for operating on iterables, beyond itertools (Python 3)
ii  python3-msgpack                            1.0.3-3+b2                           arm64        Python 3 implementation of MessagePack format
ii  python3-natsort                            8.0.2-2                              all          Natural sorting for Python (Python3)
ii  python3-netifaces:arm64                    0.11.0-2+b3                          arm64        portable network interface information - Python 3.x
ii  python3-netplan                            1.1-1                                arm64        Declarative network configuration Python bindings
ii  python3-oauthlib                           3.2.2-1                              all          generic, spec-compliant implementation of OAuth for Python3
ii  python3-packaging                          24.1-1                               all          core utilities for python3 packages
ii  python3-pexpect                            4.9-2                                all          Python 3 module for automating interactive applications
ii  python3-pil:arm64                          10.4.0-1                             arm64        Python Imaging Library (Python3)
ii  python3-pkg-resources                      74.1.2-2                             all          Package Discovery and Resource Access using pkg_resources
ii  python3-polib                              1.2.0-1                              all          Python 3 library to parse and manage gettext catalogs
ii  python3-psutil                             5.9.8-2                              arm64        module providing convenience functions for managing processes (Python3)
ii  python3-ptyprocess                         0.7.0-5                              all          Run a subprocess in a pseudo terminal from Python 3
ii  python3-py                                 1.11.0-2                             all          Advanced Python development support library (Python 3)
ii  python3-pycryptodome                       3.20.0+dfsg-3                        arm64        cryptographic Python library (Python 3)
ii  python3-pygments                           2.18.0+dfsg-1                        all          syntax highlighting package written in Python 3
ii  python3-pyparsing                          3.1.2-1                              all          alternative to creating and executing simple grammars - Python 3.x
ii  python3-pyudev                             0.24.0-1                             all          Python3 bindings for libudev
ii  python3-reportlab                          4.2.5-1                              all          ReportLab library to create PDF documents using Python3
ii  python3-requests                           2.32.3+dfsg-1                        all          elegant and simple HTTP library for Python3, built for human beings
ii  python3-rich                               13.7.1-1                             all          render rich text, tables, progress bars, syntax highlighting, markdown and more
ii  python3-rlpycairo                          0.3.0-3                              all          plugin for the ReportLab PDF Toolkit.
ii  python3-six                                1.16.0-7                             all          Python 2 and 3 compatibility library
ii  python3-software-properties                0.99.30-4.1                          all          manage the repositories that you install software from
ii  python3-speechd                            0.11.5-5                             all          Python interface to Speech Dispatcher
ii  python3-systemd                            235-1+b4                             arm64        Python 3 bindings for systemd
ii  python3-typeguard                          4.3.0-1                              all          Run-time type checker for Python
ii  python3-typing-extensions                  4.12.2-2                             all          Backported and Experimental Type Hints for Python
ii  python3-uno                                4:24.8.2-1                           arm64        Python-UNO bridge
ii  python3-urllib3                            2.0.7-2                              all          HTTP library with thread-safe connection pooling for Python3
ii  python3-wadllib                            1.3.6-5                              all          Python 3 library for navigating WADL files
ii  python3-wxgtk4.0                           4.2.2+dfsg-1                         arm64        Python 3 interface to the wxWidgets Cross-platform C++ GUI toolkit
ii  python3-xapian                             1.4.25-1+b1                          arm64        Xapian search engine interface for Python3
ii  python3-xdg                                0.28-2                               all          Python 3 library to access freedesktop.org standards
ii  python3-yaml                               6.0.2-1                              arm64        YAML parser and emitter for Python3
ii  python3-zmq                                24.0.1-5+b2                          arm64        Python3 bindings for 0MQ library
rc  python3.11-minimal                         3.11.2-6+deb12u2                     arm64        Minimal subset of the Python language (version 3.11)
ii  python3.12                                 3.12.6-1                             arm64        Interactive high-level object-oriented language (version 3.12)
ii  python3.12-minimal                         3.12.6-1                             arm64        Minimal subset of the Python language (version 3.12)

**Comment by ryecoaaron** [comment]
It looks you are either using debian testing or you upgraded python3 from another repo.  This is your problem.

**Comment by votdev** [comment]
> It looks you are either using debian testing or you upgraded python3 from another repo. This is your problem.

@ryecoaaron Thanks for looking into that.

Puh, i thought we have a bigger Problem now. It is enough that for Debian 13/OMV8 the SaltStack packaging will be a challenge.

**Comment by mckaygerhard** [comment]
why not just change the python problematic modules by another lang liike perl or bash? this is a mess, or use golang or C or i dont know.. anything more backguard and forward compatible.. perl is very forward comaptible and backguard compatible..

**Comment by votdev** [comment]
> why not just change the python problematic modules by another lang liike perl or bash? this is a mess, or use golang or C or i dont know.. anything more backguard and forward compatible.. perl is very forward comaptible and backguard compatible..

Is this a serious suggestion? This is not possible because we are talking about a 3rd party software that OMV is using. We can not change or replace anything related to this topic.

**Comment by mckaygerhard** [comment]
> This is not possible because we are talking about a 3rd party software that OMV is using. 

you are using python scripts inside OMV that can be changed to another more less changed api tool

> We can not change or replace anything related to this topic.

is not related to this topic.. i noted the ABI/API change beetween debian upgrades.. **package names becomes a hell in those cases of python**

**Comment by ryecoaaron** [comment]
All of the python packages are using the python3-* package name for the dependencies.  These upgrade just fine.  We understand you don't like python but please stop pushing to make a major change.  saltstack is python based and it makes sense to use python in many places.

**Comment by mckaygerhard** [comment]
a way to deal is wait to debian 13 and see what is ! but means time lost and next OMV will not be ready.. 

so then means right now OMV development team must deal with current dependency hell that still is not the right ones.. 

Debian 13 still is not freeze https://release.debian.org/testing/freeze_policy.html (2025/1)  and many python packages may change until such day.,. so more waste of time.. 

> stop pushing to make a major change. saltstack is python based and it makes sense to use python in many places.

please.. as example https://github.com/purpleidea/mgmt does not suffers the dependency hell! that is a fact! static compilation and that-s all.. so there are alternatives and also there are the keys to change to a more fliently to upgrades infrastructure

OMV team must lost time dealing with dependency hell now.. right?..

**Comment by votdev** [comment]
The development of the current version starts when Debian does a freeze of the upcoming version. And as always: OMV is done when it is done.
