### ISSUE TITLE
OVM after isntall  fails due rare directive in nginx config file

### ISSUE THREAD

**Issue by mckaygerhard** [openmediavault/openmediavault#1848]
**Describe the bug**

i installed OVM and after one day i just installed only the OVM fail2ban plugin.. nothing more extras.. BUT: service does not apply changes anymore..  with error

Today applied an upgrade and removed the fail2ban plugin and try agains so restart machine and got that nginx does nto run the service..

But seems your package assumes python3 non existing modules (seems there are some script made in this crap lang) that are not installed because the package installation relies on "recommends" behavior of apt check logs of initial erro at [LOGS](#logs) section of this report bug

After restart nginx gives error like `1279#1279: unknown directive "!<arch>" in /etc/nginx/sites-enabled/openmediavault-omv` checks at [Additional context](#additional-context) section of this report bug

**To Reproduce**

1. install Debian using deboostrap minimal packages
2. install OVM by apt
3. install ovm plugins only fail2ban
4. core OVM repo repost and upgrade, so i upgrade two core plugins
5. error then remove plugin but using apt only
6. reboot and then nginx does not run

**openmediavault Server (please complete the following information):**

- OS version: 

`Linux importacion 6.1.0-27-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.115-1 (2024-11-01) x86_64 GNU/Linux`

- openmediavault version: 

```
ii  openmediavault                        7.4.12-3                            all          openmediavault - The open network attached storage solution
ii  openmediavault-apt                    7.0-2                               all          openmediavault APT management plugin
ii  openmediavault-apttool                7.1.1                               all          apt tool plugin for OpenMediaVault.
ii  openmediavault-fail2ban               7.0.1                               all          OpenMediaVault Fail2ban plugin
ii  openmediavault-ftp                    7.0-5                               all          openmediavault FTP-Server plugin
ii  openmediavault-omvextrasorg           7.0                                 all          OMV-Extras.org Package Repositories for OpenMediaVault
ii  openmediavault-snmp                   7.0-2                               all          openmediavault SNMP (Simple Network Management Protocol) plugin
ii  openmediavault-wireguard              7.0.7                               all          openmediavault WireGuard plugin
```

**Client (please complete the following information):**

- Device: AMD64 16 cores i9900K
- OS: Debian 12
- Browser brave, also tested in firefox ESR
- Version lasted, 122-esr respectyivelly

### Additional context

I applied an upgrade of packages and nginx after reboot give me this error `unknown directive "!<arch>"` :

```
Nov 15 14:48:06 importacion systemd[1]: Starting nginx.service - A high performance web server and a reverse proxy server...
Nov 15 14:48:06 importacion nginx[1279]: 2024/11/15 14:48:06 [emerg] 1279#1279: unknown directive "!<arch>" in /etc/nginx/sites-enabled/openmediavault-omv>
Nov 15 14:48:06 importacion nginx[1279]: nginx: configuration file /etc/nginx/nginx.conf test failed
Nov 15 14:48:06 importacion systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
Nov 15 14:48:06 importacion systemd[1]: nginx.service: Failed with result 'exit-code'.
Nov 15 14:48:06 importacion systemd[1]: Failed to start nginx.service - A high performance web server and a reverse proxy server.
```

#### LOGS

```
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; omv-salt deploy run --no-color monit 2>&1' with exit code '1': importacion:
    Data failed to compile:
----------
    Rendering SLS 'base:omv.deploy.monit.services.proftpd' failed: Jinja error: 'NoneType' object has no attribute 'get_dict'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 477, in render_jinja_tmpl
    output = template.render(**decoded_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 20, in top-level template code
  File "/usr/lib/python3/dist-packages/jinja2/sandbox.py", line 396, in call
    return __context.call(__obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1234, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1249, in _run_as
    return _func_or_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/cache/salt/minion/extmods/modules/omv_conf.py", line 44, in get
    return objs.get_dict()
           ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_dict'

; line 20

---
[...]
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

{% set proftpd_config = salt['omv_conf.get']('conf.service.ftp') %}    <======================

{% if proftpd_config.enable | to_bool %}

{% set email_config = salt['omv_conf.get']('conf.system.notification.email') %}
{% set notification_config = salt['omv_conf.get_by_filter'](
[...]
---
[ERROR   ] Rendering exception occurred
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 477, in render_jinja_tmpl
    output = template.render(**decoded_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 20, in top-level template code
  File "/usr/lib/python3/dist-packages/jinja2/sandbox.py", line 396, in call
    return __context.call(__obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1234, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1249, in _run_as
    return _func_or_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/cache/salt/minion/extmods/modules/omv_conf.py", line 44, in get
    return objs.get_dict()
           ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_dict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 219, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 523, in render_jinja_tmpl
    raise SaltRenderError(
salt.exceptions.SaltRenderError: Jinja error: 'NoneType' object has no attribute 'get_dict'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 477, in render_jinja_tmpl
    output = template.render(**decoded_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 20, in top-level template code
  File "/usr/lib/python3/dist-packages/jinja2/sandbox.py", line 396, in call
    return __context.call(__obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1234, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1249, in _run_as
    return _func_or_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/cache/salt/minion/extmods/modules/omv_conf.py", line 44, in get
    return objs.get_dict()
           ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_dict'

; line 20

---
[...]
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

{% set proftpd_config = salt['omv_conf.get']('conf.service.ftp') %}    <======================

{% if proftpd_config.enable | to_bool %}

{% set email_config = salt['omv_conf.get']('conf.system.notification.email') %}
{% set notification_config = salt['omv_conf.get_by_filter'](
[...]
---
[CRITICAL] Rendering SLS 'base:omv.deploy.monit.services.proftpd' failed: Jinja error: 'NoneType' object has no attribute 'get_dict'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 477, in render_jinja_tmpl
    output = template.render(**decoded_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 20, in top-level template code
  File "/usr/lib/python3/dist-packages/jinja2/sandbox.py", line 396, in call
    return __context.call(__obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1234, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1249, in _run_as
    return _func_or_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/cache/salt/minion/extmods/modules/omv_conf.py", line 44, in get
    return objs.get_dict()
           ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_dict'

; line 20

---
[...]
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

{% set proftpd_config = salt['omv_conf.get']('conf.service.ftp') %}    <======================

{% if proftpd_config.enable | to_bool %}

{% set email_config = salt['omv_conf.get']('conf.system.notification.email') %}
{% set notification_config = salt['omv_conf.get_by_filter'](
[...]
---

OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; omv-salt deploy run --no-color monit 2>&1' with exit code '1': importacion:
    Data failed to compile:
----------
    Rendering SLS 'base:omv.deploy.monit.services.proftpd' failed: Jinja error: 'NoneType' object has no attribute 'get_dict'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 477, in render_jinja_tmpl
    output = template.render(**decoded_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 20, in top-level template code
  File "/usr/lib/python3/dist-packages/jinja2/sandbox.py", line 396, in call
    return __context.call(__obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1234, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1249, in _run_as
    return _func_or_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/cache/salt/minion/extmods/modules/omv_conf.py", line 44, in get
    return objs.get_dict()
           ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_dict'

; line 20

---
[...]
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

{% set proftpd_config = salt['omv_conf.get']('conf.service.ftp') %}    <======================

{% if proftpd_config.enable | to_bool %}

{% set email_config = salt['omv_conf.get']('conf.system.notification.email') %}
{% set notification_config = salt['omv_conf.get_by_filter'](
[...]
---
[ERROR   ] Rendering exception occurred
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 477, in render_jinja_tmpl
    output = template.render(**decoded_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 20, in top-level template code
  File "/usr/lib/python3/dist-packages/jinja2/sandbox.py", line 396, in call
    return __context.call(__obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1234, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1249, in _run_as
    return _func_or_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/cache/salt/minion/extmods/modules/omv_conf.py", line 44, in get
    return objs.get_dict()
           ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_dict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 219, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 523, in render_jinja_tmpl
    raise SaltRenderError(
salt.exceptions.SaltRenderError: Jinja error: 'NoneType' object has no attribute 'get_dict'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 477, in render_jinja_tmpl
    output = template.render(**decoded_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 20, in top-level template code
  File "/usr/lib/python3/dist-packages/jinja2/sandbox.py", line 396, in call
    return __context.call(__obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1234, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1249, in _run_as
    return _func_or_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/cache/salt/minion/extmods/modules/omv_conf.py", line 44, in get
    return objs.get_dict()
           ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_dict'

; line 20

---
[...]
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

{% set proftpd_config = salt['omv_conf.get']('conf.service.ftp') %}    <======================

{% if proftpd_config.enable | to_bool %}

{% set email_config = salt['omv_conf.get']('conf.system.notification.email') %}
{% set notification_config = salt['omv_conf.get_by_filter'](
[...]
---
[CRITICAL] Rendering SLS 'base:omv.deploy.monit.services.proftpd' failed: Jinja error: 'NoneType' object has no attribute 'get_dict'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 477, in render_jinja_tmpl
    output = template.render(**decoded_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 20, in top-level template code
  File "/usr/lib/python3/dist-packages/jinja2/sandbox.py", line 396, in call
    return __context.call(__obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1234, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1249, in _run_as
    return _func_or_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/cache/salt/minion/extmods/modules/omv_conf.py", line 44, in get
    return objs.get_dict()
           ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_dict'

; line 20

---
[...]
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

{% set proftpd_config = salt['omv_conf.get']('conf.service.ftp') %}    <======================

{% if proftpd_config.enable | to_bool %}

{% set email_config = salt['omv_conf.get']('conf.system.notification.email') %}
{% set notification_config = salt['omv_conf.get_by_filter'](
[...]
--- in /usr/share/php/openmediavault/system/process.inc:247
Stack trace:
#0 /usr/share/php/openmediavault/engine/module/serviceabstract.inc(62): OMV\System\Process->execute()
#1 /usr/share/openmediavault/engined/rpc/config.inc(187): OMV\Engine\Module\ServiceAbstract->deploy()
#2 [internal function]: Engined\Rpc\Config->applyChanges()
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(122): call_user_func_array()
#4 /usr/share/php/openmediavault/rpc/serviceabstract.inc(149): OMV\Rpc\ServiceAbstract->callMethod()
#5 /usr/share/php/openmediavault/rpc/serviceabstract.inc(622): OMV\Rpc\ServiceAbstract->OMV\Rpc\{closure}()
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(146): OMV\Rpc\ServiceAbstract->execBgProc()
#7 /usr/share/openmediavault/engined/rpc/config.inc(208): OMV\Rpc\ServiceAbstract->callMethodBg()
#8 [internal function]: Engined\Rpc\Config->applyChangesBg()
#9 /usr/share/php/openmediavault/rpc/serviceabstract.inc(122): call_user_func_array()
#10 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod()
#11 /usr/sbin/omv-engined(544): OMV\Rpc\Rpc::call()
#12 {main}
```

**Comment by ryecoaaron** [comment]
Looks like the ftp plugin section of the omv database was corrupt and the saltstack code was finding unexpected settings.  It doesn't look like a fail2ban or python issue to me.  Removing the ftp plugin would've removed the corrupt ftp settings and as expected, fixed the issue.  I don't know what happened in the ftp install but I have ftp and fail2ban installed on my dev system without issue.  I would imagine that reinstalling the ftp plugin would go ok and this problem would not reoccur.

**Comment by mckaygerhard** [comment]
i already have also the ftp plugin installed in a test VM environment.. but as i cited @ryecoaaron  i was happened after an upgrade/update of the plugin today! seems there a missing python crap module cos in my isntallation i do not use "recommends" package so many packages are not installed by default that maybe are assumed

**Comment by ryecoaaron** [comment]
If the fail2ban was updated, it would not corrupt the ftp plugin's database section though even if possible fail2ban dependencies were missing.  The ftp plugin doesn't use python if you remove the system applying settings with saltstack.

I am curious how you had a fail2ban plugin update since I haven't updated the plugin in 10+ months.  Do you have the /var/log/apt/term.log?

**Comment by ryecoaaron** [comment]
I will also mention that I don't testing install plugins using --no-install-recommends.  I install them from the web interface which does not pass that flag.  If you have problems installing from the command with that flag, you are going to have to figure out what dependency is not getting installed and report it.

**Comment by mckaygerhard** [comment]
> I don't test installing plugins using --no-install-recommends. I install them from the web interface which does not pass that flag

its by default as is.. no matter if you installed from web.. and is not a problem and should dont be so  cos the package must manage the correct dependencies.. 

if the package xxx does need specific python module **must** list in their dependencies..  

cos i manage and does the minimal install using the debootstrap and reduced the size of the database packages.. a valid way and official one from debian the supported operatin system..

**Comment by ryecoaaron** [comment]
> its by default as is.. no matter if you installed from web.. and is not a problem and should dont be so cos the package must manage the correct dependencies..

I know how packaging works but I only have so much time to do testing.  It doesn't matter how you install the OS.  Just the plugin.  If have to start from a clean system every time I install a plugin, it would take me forever to test.  I don't have that time.  I try to list all dependencies but some might get missed.

>  if the package xxx does need specific python module must list in their dependencies..

Obviously I test plugins.  If my testing doesn't show a problem, then I would assume all of the dependencies are listed in the control file.  I am just stating that if you find one missing, please report it.

**Comment by votdev** [comment]
> if the package xxx does need specific python module **must** list in their dependencies..

All OMV packages have valid dependency lists of the packages they need.

**Comment by votdev** [comment]
> Nov 15 14:48:06 importacion nginx[1279]: 2024/11/15 14:48:06 [emerg] 1279#1279: unknown directive "!<arch>" in /etc/nginx/sites-enabled/openmediavault-omv>

This file is not owned by OMV. What is the content of this file. According to the error message the syntax is invalid.

**Comment by votdev** [comment]
> Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; omv-salt deploy run --no-color monit 2>&1' with exit code '1': importacion:
    Data failed to compile:
----------
    Rendering SLS 'base:omv.deploy.monit.services.proftpd' failed: Jinja error: 'NoneType' object has no attribute 'get_dict'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 477, in render_jinja_tmpl

> {% set proftpd_config = salt['omv_conf.get']('conf.service.ftp') %}    <======================

There are several corrupted database errors reported here. Have you modified the database manually? Both errors are mostly occur when database migration scripts are not performed during package installation because of package installation was broken or aborted.
