### ISSUE TITLE
omv-5.0: install error

### ISSUE THREAD

**Issue by darcyg** [openmediavault/openmediavault#241]
hi,
  omv 5.0 git ver , install error

Setting up Salt environment ...
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1913, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1898, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/states/saltmod.py", line 762, in runner
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/saltutil.py", line 1524, in runner
    full_return=full_return)
  File "/usr/lib/python2.7/dist-packages/salt/runner.py", line 156, in cmd
    full_return)
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 233, in cmd
    self.functions[fun], arglist, pub_data
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1155, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "/usr/lib/python2.7/dist-packages/salt/utils/lazy.py", line 101, in __getitem__
    return self._dict[key]
KeyError: u'omv.populate_pillar'

dpkg: error processing package openmediavault (--install):
 installed openmediavault package post-installation script subprocess returned error exit status 2
Processing triggers for rsyslog (8.32.0-1ubuntu4) ...
Errors were encountered while processing:
 openmediavault

**Comment by votdev** [comment]
OMV5 does not support Python2. You need to install the correct Salt version which uses Python3.

**Comment by votdev** [comment]
The openmediavault Debian [package control file](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/debian/control#L27) clearly tells this that Salt 2018.3.3 must be used.

**Comment by votdev** [comment]
And note that OMV5 does not work on Ubuntu, it's tied to Debian only.

**Comment by darcyg** [comment]
thks 
testing now....

**Comment by darcyg** [comment]
hi votdev:
  I would like to ask how to build an image of my own debian iso + omv package.
Can you explain the build process and the software used?
thks

**Comment by votdev** [comment]
To build your own ISO simply use live-build.
