### ISSUE TITLE
The property options does not exist in the model conf.system.network.interface

### ISSUE THREAD

**Issue by fransvanberckel** [openmediavault/openmediavault#282]
While installing the omv5 package on a fresh Debian system, running # omv-confdbadm populate, error; The property 'options' does not exist in the model 'conf.system.network.interface'.

A step before it gave an error message: AttributeError: module 'salt.ext' has no attribute 'ipaddress', but i have patched salt/modules/network.py to solve that issue.

Did I miss something while setup?

Traceback (most recent call last):
  File "/usr/sbin/omv-confdbadm", line 74, in <module>
    sys.exit(main())
  File "/usr/sbin/omv-confdbadm", line 70, in main
    return cmd_inst.execute(*sys.argv)
  File "/usr/share/openmediavault/confdbadm/commands.d/update.py", line 56, in execute
    obj.set_dict(cmd_args.data)
  File "/usr/lib/python3/dist-packages/openmediavault/config/object.py", line 206, in set_dict
    self.set(key, value, validate)
  File "/usr/lib/python3/dist-packages/openmediavault/config/object.py", line 180, in set
    self.assert_exists(name)
  File "/usr/lib/python3/dist-packages/openmediavault/config/object.py", line 152, in assert_exists
    (name, self.model.id)
openmediavault.exceptions.AssertException: The property 'options' does not exist in the model 'conf.system.network.interface'.
Traceback (most recent call last):
  File "/usr/sbin/omv-confdbadm", line 74, in <module>
    sys.exit(main())
  File "/usr/sbin/omv-confdbadm", line 70, in main
    return cmd_inst.execute(*sys.argv)
  File "/usr/share/openmediavault/confdbadm/commands.d/populate.py", line 48, in execute
    openmediavault.subprocess.check_call([script_path])
  File "/usr/lib/python3/dist-packages/openmediavault/subprocess.py", line 58, in check_call
    return subprocess.check_call(*popenargs, **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/share/openmediavault/confdb/populate.d/40interfaces.sh']' returned non-zero exit status 1

**Comment by henfri** [comment]
Hello Volker,

unfortunately, I have the same problem, although the patch 6768ee9 seems to be applied on my computer.
Any idea?

Regards,
Hendrik

**Comment by votdev** [comment]
> Hello Volker,
> 
> unfortunately, I have the same problem, although the patch [6768ee9](https://github.com/openmediavault/openmediavault/commit/6768ee9566b18558de68d36708641551d0e1be5f) seems to be applied on my computer.
> Any idea?
> 
> Regards,
> Hendrik

Any hint how to reproduce this?

**Comment by henfri** [comment]
Hello,

yes, I run omv-confdbadm populate:

```
root@homeserver:~# omv-confdbadm populate
Traceback (most recent call last):
  File "/usr/sbin/omv-confdbadm", line 74, in <module>
    sys.exit(main())
  File "/usr/sbin/omv-confdbadm", line 70, in main
    return cmd_inst.execute(*sys.argv)
  File "/usr/share/openmediavault/confdbadm/commands.d/exists.py", line 54, in execute
    return 0 if db.exists(cmd_args.id, filter) else 1
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 164, in exists
    query.execute()
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 683, in execute
    self._response = self._elements_to_object(elements)
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 467, in _elements_to_object
    obj.set_dict(self._element_to_dict(element), False)
  File "/usr/lib/python3/dist-packages/openmediavault/config/object.py", line 207, in set_dict
    self.set(key, value, validate)
  File "/usr/lib/python3/dist-packages/openmediavault/config/object.py", line 181, in set
    self.assert_exists(name)
  File "/usr/lib/python3/dist-packages/openmediavault/config/object.py", line 153, in assert_exists
    % (name, self.model.id)
openmediavault.exceptions.AssertException: The property 'options' does not exist in the model 'conf.system.network.interface'.
[WARNING ] /usr/lib/python3/dist-packages/salt/utils/decorators/signature.py:31: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
  *salt.utils.args.get_function_argspec(original_function)

[WARNING ] /usr/lib/python3/dist-packages/salt/utils/decorators/signature.py:31: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
  *salt.utils.args.get_function_argspec(original_function)

```

maybe related: After running omv-firstaid I get 
```
Configuring network interface. Please wait ...
ERROR: __init__() got an unexpected keyword argument 'http_status_code'

```

Greetings,
Hendrik

**Comment by votdev** [comment]
@henfri According to the error message your systems seems to be upgraded from OMV4 to OMV5. During that your database has not been migrated correctly.
Try to fix it with `omv-confdbadm migrate conf 5.0.0`.

**Comment by henfri** [comment]
Thank you. That fixed it!

Thanks for your work on OMV. I appreciate it!
