### ISSUE TITLE
Can't update on new install of OMV 4

### ISSUE THREAD

**Issue by patrick-motard** [openmediavault/openmediavault#391]
### Description of issue/question
I am not able to install updates. The update button in OMV doesn't work either. Not able to install omv-extras as well. Stack trace below. Seems related to a missing cert perhaps?

### Steps to reproduce issue
(Include debug logs if possible and relevant.)
```
~# apt-get update
Get:1 file:/var/cache/openmediavault/archives  InRelease
Ign:1 file:/var/cache/openmediavault/archives  InRelease
Get:2 file:/var/cache/openmediavault/archives  Release
Ign:2 file:/var/cache/openmediavault/archives  Release
Get:3 file:/var/cache/openmediavault/archives  Packages
Ign:3 file:/var/cache/openmediavault/archives  Packages
Get:4 file:/var/cache/openmediavault/archives  Translation-en
Ign:4 file:/var/cache/openmediavault/archives  Translation-en
Get:3 file:/var/cache/openmediavault/archives  Packages
Ign:3 file:/var/cache/openmediavault/archives  Packages
Get:4 file:/var/cache/openmediavault/archives  Translation-en
Ign:4 file:/var/cache/openmediavault/archives  Translation-en
Get:3 file:/var/cache/openmediavault/archives  Packages
Ign:3 file:/var/cache/openmediavault/archives  Packages
Get:4 file:/var/cache/openmediavault/archives  Translation-en
Ign:4 file:/var/cache/openmediavault/archives  Translation-en
Get:3 file:/var/cache/openmediavault/archives  Packages
Ign:3 file:/var/cache/openmediavault/archives  Packages
Get:4 file:/var/cache/openmediavault/archives  Translation-en
Ign:4 file:/var/cache/openmediavault/archives  Translation-en
Get:3 file:/var/cache/openmediavault/archives  Packages
Ign:3 file:/var/cache/openmediavault/archives  Packages
Get:4 file:/var/cache/openmediavault/archives  Translation-en
Ign:4 file:/var/cache/openmediavault/archives  Translation-en
Get:3 file:/var/cache/openmediavault/archives  Packages [1100 B]
Get:4 file:/var/cache/openmediavault/archives  Translation-en
Ign:4 file:/var/cache/openmediavault/archives  Translation-en
Hit:5 http://security.debian.org/debian-security stretch/updates InRelease
Ign:6 http://ftp.us.debian.org/debian stretch InRelease                  
Ign:7 https://openmediavault.github.io/packages arrakis InRelease        
Hit:8 http://ftp.us.debian.org/debian stretch-updates InRelease          
Hit:10 http://ftp.us.debian.org/debian stretch Release                                                                                                   
Hit:9 http://cdn-fastly.deb.debian.org/debian stretch-backports InRelease                                                                                
Ign:11 https://openmediavault.github.io/packages arrakis Release                                               
Ign:12 https://openmediavault.github.io/packages arrakis/main all Packages               
Ign:13 https://dl.bintray.com/openmediavault-plugin-developers/arrakis stretch InRelease
Ign:15 https://openmediavault.github.io/packages arrakis/main amd64 Packages            
Hit:16 http://packages.openmediavault.org/public arrakis InRelease
Ign:17 https://openmediavault.github.io/packages arrakis/main Translation-en
Ign:12 https://openmediavault.github.io/packages arrakis/main all Packages
Ign:18 https://dl.bintray.com/openmediavault-plugin-developers/arrakis stretch Release
Ign:15 https://openmediavault.github.io/packages arrakis/main amd64 Packages
Ign:17 https://openmediavault.github.io/packages arrakis/main Translation-en
Ign:12 https://openmediavault.github.io/packages arrakis/main all Packages
Ign:19 https://dl.bintray.com/openmediavault-plugin-developers/arrakis stretch/main amd64 Packages
Ign:15 https://openmediavault.github.io/packages arrakis/main amd64 Packages
Ign:17 https://openmediavault.github.io/packages arrakis/main Translation-en
Ign:12 https://openmediavault.github.io/packages arrakis/main all Packages
Ign:15 https://openmediavault.github.io/packages arrakis/main amd64 Packages
Ign:20 https://dl.bintray.com/openmediavault-plugin-developers/arrakis stretch/main all Packages
Ign:17 https://openmediavault.github.io/packages arrakis/main Translation-en
Ign:12 https://openmediavault.github.io/packages arrakis/main all Packages
Ign:15 https://openmediavault.github.io/packages arrakis/main amd64 Packages
Ign:21 https://dl.bintray.com/openmediavault-plugin-developers/arrakis stretch/main Translation-en
Ign:17 https://openmediavault.github.io/packages arrakis/main Translation-en
Ign:12 https://openmediavault.github.io/packages arrakis/main all Packages
Err:15 https://openmediavault.github.io/packages arrakis/main amd64 Packages
  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
Ign:19 https://dl.bintray.com/openmediavault-plugin-developers/arrakis stretch/main amd64 Packages
Ign:17 https://openmediavault.github.io/packages arrakis/main Translation-en
Ign:20 https://dl.bintray.com/openmediavault-plugin-developers/arrakis stretch/main all Packages
Ign:21 https://dl.bintray.com/openmediavault-plugin-developers/arrakis stretch/main Translation-en
Ign:19 https://dl.bintray.com/openmediavault-plugin-developers/arrakis stretch/main amd64 Packages
Ign:20 https://dl.bintray.com/openmediavault-plugin-developers/arrakis stretch/main all Packages
Ign:21 https://dl.bintray.com/openmediavault-plugin-developers/arrakis stretch/main Translation-en
Ign:19 https://dl.bintray.com/openmediavault-plugin-developers/arrakis stretch/main amd64 Packages
Ign:20 https://dl.bintray.com/openmediavault-plugin-developers/arrakis stretch/main all Packages
Ign:21 https://dl.bintray.com/openmediavault-plugin-developers/arrakis stretch/main Translation-en
Ign:19 https://dl.bintray.com/openmediavault-plugin-developers/arrakis stretch/main amd64 Packages
Ign:20 https://dl.bintray.com/openmediavault-plugin-developers/arrakis stretch/main all Packages
Ign:21 https://dl.bintray.com/openmediavault-plugin-developers/arrakis stretch/main Translation-en
Err:19 https://dl.bintray.com/openmediavault-plugin-developers/arrakis stretch/main amd64 Packages
  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
Ign:20 https://dl.bintray.com/openmediavault-plugin-developers/arrakis stretch/main all Packages
Ign:21 https://dl.bintray.com/openmediavault-plugin-developers/arrakis stretch/main Translation-en
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f7b58dbd7b8>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f7b58dbd7b8>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Reading package lists... Done
W: The repository 'https://openmediavault.github.io/packages arrakis Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: The repository 'https://dl.bintray.com/openmediavault-plugin-developers/arrakis stretch Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://openmediavault.github.io/packages/dists/arrakis/main/binary-amd64/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
E: Failed to fetch https://dl.bintray.com/openmediavault-plugin-developers/arrakis/dists/stretch/main/binary-amd64/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by ryecoaaron** [comment]
Make sure your system time is correct.  Enabling ntp is the easiest way to do this.

**Comment by patrick-motard** [comment]
A fellow Wisconsinite comes to the rescue! Thank you @ryecoaaron! Turns out ntp was already installed, but it was not enabled in OMV (System > Date Time > Settings > Use NTP Server). Once i enabled it and re-logged in I was able to check for updates, and install omv-extras.

**Comment by votdev** [comment]
@ryecoaaron Can you tell me more about why NTP solves this issue?

**Comment by ryecoaaron** [comment]
@votdev, on machines not running ntp, the time could be wrong. This is common on arm boards because the time resets to the beginning of the unix epoch when they are powered on. When certs have a creation timestamp in the distant future, apt and ssl are unhappy causing this issue. since the release file is signed with a signing key that has a creation date in the future as well, that repo is ignored.

**Comment by votdev** [comment]
@ryecoaaron Thanks for the explanation.

**Comment by donhwy** [comment]
Time zone not set properly can also cause this. FYI

**Comment by mackonsti** [comment]
Hello everyone, I would like to re-open this ticket as I am getting the same error today. My NTP service is running OK, time/date is correct and region set correctly too. I rebooted twice. Just today all of a sudden I get the same error (either via UI or SSH):

`E: The repository 'https://dl.bintray.com/openmediavault-plugin-developers/arrakis stretch Release' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.`

Is there something wrong with the actual server perhaps? Even the OMV forum seems down for maintenance and will be for some days, per the message shown. Thank you!

**Comment by arnaudclca** [comment]
Hi,
I have the same problem. I'm on OMV 4.1.35-1. Have you found a solution in the last weeks?

**Comment by ryecoaaron** [comment]
This is a bintray issue from time to time. It shouldn’t be a problem for a long time. Try apt clean from omv-extras

**Comment by arnaudclca** [comment]
Hi,
Yes, I've done the apt clean. 

Finally, my problem was that I had edit the sources.list to add repositories. As the old sources for OMV3 (Jessie) were removed and then moved to Debian's archive, I wasn't able to find them. 

With a broken reprositories list, I first only succeed to update partially (that when the issue occured at first.

So I had to remove the added reprositories from the sources.list file that were related to Jessie version and voilà, the omv-update works fine.

Basic verification 
-ntp server on (system clock and timezone)
-had tried apt-get clean
-had tried omv-mkconf apt
-install the omv-extras  (https://forum.openmediavault.org/index.php?thread/5549-omv-extras-org-plugin/)

So, my solution (for me) : 
as root using putty
nano /etc/apt/sources.list 
removed old source list line related to 

crtl+o to save
the enter (accept to write file)
crtl+x to quit editing file.

omv-update

usefull link : 
https://openmediavault.readthedocs.io/en/5.x/various/apt.html
https://unix.stackexchange.com/questions/508724/failed-to-fetch-jessie-backports-repository
https://linoxide.com/debian/configure-sources-list-debian-9/
https://debian-facile.org/viewtopic.php?id=15895
https://www.networkworld.com/article/3453032/cleaning-up-with-apt-get.html

and most of all : Google.
