### ISSUE TITLE
Raspberry 4: OMV 2019-07-17 python exception from `apt update`

### ISSUE THREAD

**Issue by PieBru** [openmediavault/openmediavault#427]
Hi, same system as in #425, the `sources.list` errors aren't harmful.

The python exception `"/usr/lib/python3.5/weakref.py", line 117, in remove` seems the same issue discussed [here](https://github.com/ayufan-rock64/linux-build/issues/136).

```
root@openmediavault:~# apt update
Get:1 file:/var/cache/openmediavault/archives  InRelease
Ign:1 file:/var/cache/openmediavault/archives  InRelease
...
Get:11 http://cdn-fastly.deb.debian.org/debian stretch-backports InRelease [91.8 kB]
Hit:16 http://cdn-fastly.deb.debian.org/debian stretch Release   
Fetched 183 kB in 3s (50.3 kB/s)                    
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0xb6255390>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0xb6255390>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Reading package lists... Done
Building dependency tree       
Reading state information... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.
W: Target Packages (main/binary-armhf/Packages) is configured multiple times in /etc/apt/sources.list:7 and /etc/apt/sources.list.d/openmediavault-kernel-backports.list:1
... lot of these ...
W: Target Contents-deb (non-free/Contents-all) is configured multiple times in /etc/apt/sources.list:7 and /etc/apt/sources.list.d/openmediavault-kernel-backports.list:1
root@openmediavault:~# cat /etc/apt/sources.list.d/openmediavault-kernel-backports.list
deb http://httpredir.debian.org/debian stretch-backports main contrib non-free
root@openmediavault:~# cat /etc/apt/sources.list | grep stretch-backports
deb http://httpredir.debian.org/debian stretch-backports main contrib non-free
#deb-src http://httpredir.debian.org/debian stretch-backports main contrib non-free
root@openmediavault:~# 
```

Thanks,
Piero

**Comment by votdev** [comment]
You can force OMV to do not write the backports repo configuration by adding ``OMV_APT_USE_KERNEL_BACKPORTS=NO`` to ``/etc/default/openmediavault`` and executing ``omv-mkconf apt``. It is out of control of OMV how upstream projects which are using OMV configure their systems. Normally it would be their part to ship an adapted ``/etc/default/openmediavault`` to prevent such issues.

The Python wakref.py issue must be fixed by the upstream Debian project, OMV consumes but can't maintain Debian packages.

**Comment by ryecoaaron** [comment]
@PieBru If you find any other issues with the arm images, can you please post on forum or the new repo I made just for arm-images - https://github.com/OpenMediaVault-Plugin-Developers/arm-images/issues

**Comment by PieBru** [comment]
OK, thanks all.
Piero
