### ISSUE TITLE
Applying firewall rules fails

### ISSUE THREAD

**Issue by vbraun** [openmediavault/openmediavault#454]
### Steps to reproduce issue

Go to Network -> Firewall

Add firewall rule

Set Action = ACCEPT
Set Destination port = 3000

Press Save, then Apply.

~~~~
Error #0:
OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-salt deploy run iptables 2>&1' with exit code '1': /usr/lib/python3/dist-packages/salt/modules/file.py:32: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Iterable, Mapping
/usr/lib/python3/dist-packages/salt/utils/decorators/signature.py:31: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
  *salt.utils.args.get_function_argspec(original_function)
/usr/lib/python3/dist-packages/salt/utils/decorators/signature.py:31: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
  *salt.utils.args.get_function_argspec(original_function)
debian:
----------
          ID: configure_firewall_script
    Function: file.managed
        Name: /etc/iptables/openmediavault-firewall.sh
      Result: True
     Comment: File /etc/iptables/openmediavault-firewall.sh is in the correct state
     Started: 14:06:35.675836
    Duration: 353.858 ms
     Changes:
----------
          ID: configure_firewall_unit_file
    Function: file.managed
        Name: /etc/systemd/system/openmediavault-firewall.service
      Result: True
     Comment: File /etc/systemd/system/openmediavault-firewall.service is in the correct state
     Started: 14:06:36.030227
    Duration: 8.638 ms
     Changes:
----------
          ID: iptables_systemctl_daemon_reload
    Function: module.run
        Name: service.systemctl_reload
      Result: True
     Comment:
     Started: 14:06:36.041219
    Duration: 1.59 ms
     Changes:
----------
          ID: enable_firewall_service
    Function: service.enabled
        Name: openmediavault-firewall.service
      Result: True
     Comment: Service openmediavault-firewall.service is already enabled, and is in the desired state
     Started: 14:06:42.873835
    Duration: 79.22 ms
     Changes:
----------
          ID: restart_firewall_service
    Function: module.run
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 1919, in call
                  **cdata['kwargs'])
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 1918, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/utils/decorators/__init__.py", line 558, in _decorate
                  return self._call_function(kwargs)
                File "/usr/lib/python3/dist-packages/salt/utils/decorators/__init__.py", line 263, in _call_function
                  raise error
                File "/usr/lib/python3/dist-packages/salt/utils/decorators/__init__.py", line 250, in _call_function
                  return self._function(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/module.py", line 294, in run
                  func_args=kwargs.get(func))
                File "/usr/lib/python3/dist-packages/salt/states/module.py", line 358, in _call_function
                  mret = __salt__[name](*arg_type, **func_kw)
                File "/usr/lib/python3/dist-packages/salt/modules/systemd.py", line 906, in restart
                  raise CommandExecutionError(_strip_scope(ret['stderr']))
              salt.exceptions.CommandExecutionError: Job for openmediavault-firewall.service failed because the control process exited with error code.
              See "systemctl status openmediavault-firewall.service" and "journalctl -xe" for details.
     Started: 14:06:42.954137
    Duration: 133.324 ms
     Changes:

Summary for debian
------------
Succeeded: 4
Failed:    1
------------
Total states run:     5
Total run time: 576.630 ms in /usr/share/php/openmediavault/system/process.inc:182
Stack trace:
#0 /usr/share/php/openmediavault/engine/module/serviceabstract.inc(60): OMV\System\Process->execute()
#1 /usr/share/openmediavault/engined/rpc/config.inc(164): OMV\Engine\Module\ServiceAbstract->deploy()
#2 [internal function]: Engined\Rpc\Config->applyChanges(Array, Array)
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#4 /usr/share/php/openmediavault/rpc/serviceabstract.inc(149): OMV\Rpc\ServiceAbstract->callMethod('applyChanges', Array, Array)
#5 /usr/share/php/openmediavault/rpc/serviceabstract.inc(588): OMV\Rpc\ServiceAbstract->OMV\Rpc\{closure}('/tmp/bgstatusBb...', '/tmp/bgoutputkp...')
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(159): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure))
#7 /usr/share/openmediavault/engined/rpc/config.inc(186): OMV\Rpc\ServiceAbstract->callMethodBg('applyChanges', Array, Array)
#8 [internal function]: Engined\Rpc\Config->applyChangesBg(Array, Array)
#9 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#10 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('applyChangesBg', Array, Array)
#11 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('Config', 'applyChangesBg', Array, Array, 1)
#12 {main}
~~~~

Output of systemctl status openmediavault-firewall.service:
~~~~
● openmediavault-firewall.service - openmediavault iptables firewall service
   Loaded: loaded (/etc/systemd/system/openmediavault-firewall.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2019-09-19 14:06:43 CEST; 7min ago
  Process: 10531 ExecStart=/etc/iptables/openmediavault-firewall.sh start (code=exited, status=4)
 Main PID: 10531 (code=exited, status=4)

Sep 19 14:06:43 vault.local systemd[1]: Starting openmediavault iptables firewall service...
Sep 19 14:06:43 vault.local openmediavault-firewall.sh[10531]: iptables v1.8.2 (nf_tables):  CHAIN_USER_DEL failed (Device or resource busy): chain DO
Sep 19 14:06:43 vault.local systemd[1]: openmediavault-firewall.service: Main process exited, code=exited, status=4/NOPERMISSION
Sep 19 14:06:43 vault.local systemd[1]: openmediavault-firewall.service: Failed with result 'exit-code'.
Sep 19 14:06:43 vault.local systemd[1]: Failed to start openmediavault iptables firewall service.
~~~~

### Versions report

5.0.8-1

~~~~
$ dpkg -l | grep openmediavault
ii  openmediavault                    5.0.8-1                     all          openmediavault - The open network attached storage solution
ii  openmediavault-diskstats          5.0-1                       all          OpenMediaVault disk monitoring plugin
ii  openmediavault-keyring            1.0                         all          GnuPG archive keys of the OpenMediaVault archive
ii  openmediavault-omvextrasorg       5.0.7                       all          OMV-Extras.org Package Repositories for OpenMediaVault
~~~~

**Comment by votdev** [comment]
Sadly i'm not able to reproduce this. So could you please open ``/etc/iptables/openmediavault-firewall.sh`` and modify the shebang to ``#!/bin/sh -x``. After that execute ``/etc/iptables/openmediavault-firewall.sh`` and post the error that hopefully will be shown.

**Comment by votdev** [comment]
Could you please post the complete line ``iptables v1.8.2 (nf_tables):  CHAIN_USER_DEL failed (Device or resource busy): chain DO``. It would be helpful to see the whole error message.

**Comment by votdev** [comment]
Are you using docker? 

Found a post with the same output ``iptables v1.8.2 (nf_tables):  CHAIN_USER_DEL failed (Device or resource busy): chain DOCKER`` :-)

https://blog.printk.io/2018/06/iptable-prevents-nftables-to-be-loaded/

**Comment by votdev** [comment]
Does it fail when you start or stop ``openmediavault-firewall.service``?

**Comment by vbraun** [comment]
Ah yes, I did install docker via omv-extras. No containers are currently running.
~~~
$ dpkg -l | grep docker
ii  docker-ce                         5:19.03.2~3-0~debian-buster amd64        Docker: the open-source application container engine
ii  docker-ce-cli                     5:19.03.2~3-0~debian-buster amd64        Docker CLI: the open-source application container engine
~~~
The systemctl log isn't much more helpful without ellipsis
~~~~
# systemctl status --full openmediavault-firewall.service | cat
● openmediavault-firewall.service - openmediavault iptables firewall service
   Loaded: loaded (/etc/systemd/system/openmediavault-firewall.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2019-09-19 15:53:39 CEST; 43s ago
  Process: 17144 ExecStart=/etc/iptables/openmediavault-firewall.sh start (code=exited, status=4)
 Main PID: 17144 (code=exited, status=4)

Sep 19 15:53:39 vault.local systemd[1]: Starting openmediavault iptables firewall service...
Sep 19 15:53:39 vault.local openmediavault-firewall.sh[17144]: iptables v1.8.2 (nf_tables):  CHAIN_USER_DEL failed (Device or resource busy): chain DOCKER
Sep 19 15:53:39 vault.local systemd[1]: openmediavault-firewall.service: Main process exited, code=exited, status=4/NOPERMISSION
Sep 19 15:53:39 vault.local systemd[1]: openmediavault-firewall.service: Failed with result 'exit-code'.
Sep 19 15:53:39 vault.local systemd[1]: Failed to start openmediavault iptables firewall service.
~~~~
The culprit is
~~~~
root@vault:/var/log# iptables -X
iptables v1.8.2 (nf_tables):  CHAIN_USER_DEL failed (Device or resource busy): chain DOCKER
~~~~
in /etc/iptables/openmediavault-firewall.sh

**Comment by votdev** [comment]
What happens when you stop Docker before?

**Comment by vbraun** [comment]
Stopping docker doesn't remove its iptables entries:
~~~~
root@vault:~# systemctl stop docker
root@vault:~# iptables -X
iptables v1.8.2 (nf_tables):  CHAIN_USER_DEL failed (Device or resource busy): chain DOCKER
~~~~

**Comment by votdev** [comment]
Hmmm, i've currently no ideas how to fix that.

**Comment by vbraun** [comment]
The openmediavault-firewall.sh script only touches INPUT and OUTPUT, I don't understand why one would want to delete other chains without knowing what they are. Presumably there is a reason for why the user set them up. So one possibility would be to remove the "iptables -X" altogether.

Another option would be to just ignore errors; For the record if I change the script to 
~~~
iptables -X || /bin/true
~~~
(simlarly the ip6tables) then `systemctl start openmediavault-firewall.service` works, so at least there is no further issue.

**Comment by votdev** [comment]
Now it's (more or less) the same behaviour as in OMV4 again.
