### ISSUE TITLE
Jinja error in openmediavault-omvextrasorg.postinst

### ISSUE THREAD

**Issue by hellfyre** [openmediavault/openmediavault#533]
### Description of issue/question
_Short_: When I try to update the debian package openmediavault-omvextrasorg, installation of the new package fails silently in postinst.

_Detailed_: I recently updated my system from stretch to buster. Since then, the package openmediavault-omvextrasorg doesn't install cleanly. The first two updates I ignored the error, but I'm beginning to think there's a problematic configuration specific to my system.
The update fails when the postinst script tries to run `omv-salt deploy run --quiet omvextras`.
When I try to run it by hand, omitting the --quiet switch, it tells me there's something missing in a Jinja template:

```
root@prometheus /h/matthias# omv-salt deploy run omvextras
prometheus.local:
    Data failed to compile:
----------
    Rendering SLS 'base:omv.deploy.omvextras.default' failed: Jinja error: The property 'repos.repo.uuid' does not exist in the model 'conf.system.omvextras'.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 393, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 18, in top-level template code
  File "/var/cache/salt/minion/extmods/modules/omv_conf.py", line 39, in get
    objs = db.get(id_, identifier)
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 85, in get
    query.execute()
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 709, in execute
    self._response = self._elements_to_object(elements)
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 470, in _elements_to_object
    result.set_dict(self._element_to_dict(elements[0]), False)
  File "/usr/lib/python3/dist-packages/openmediavault/config/object.py", line 207, in set_dict
    self.set(key, value, validate)
  File "/usr/lib/python3/dist-packages/openmediavault/config/object.py", line 181, in set
    self.assert_exists(name)
  File "/usr/lib/python3/dist-packages/openmediavault/config/object.py", line 153, in assert_exists
    % (name, self.model.id)
openmediavault.exceptions.AssertException: The property 'repos.repo.uuid' does not exist in the model 'conf.system.omvextras'.

; line 18

---
[...]
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

{% set config = salt['omv_conf.get']('conf.system.omvextras') %}    <======================
{% set use_kernel_backports = salt['pillar.get']('default:OMV_APT_USE_KERNEL_BACKPORTS', True) -%}

configure_apt_sources_list_omvextras:
  file.managed:
    - name: "/etc/apt/sources.list.d/omvextras.list"
[...]
---
```

### Steps to reproduce issue
Update the package openmediavault-omvextrasorg on Debian Buster to version 5.1.9. Like I said before: This might be specific to my system, since I upgraded to buster.

### Versions report
Package | Version
--- | ---
openmediavault | 5.1.2-1
openmediavault-keyring | 1.0
openmediavault-omvextrasorg | 5.1.9
openmediavault-usbbackup | 5.0.2-1
openmediavault-zfs | 5.0.1

**Comment by ryecoaaron** [comment]
This is definitely caused by the upgrade.  There is probably some database config that didn't get purged.  Please post on the omv-extras repo - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg/issues and post the output of omv-showkey omvextras

**Comment by votdev** [comment]
@ry

**Comment by hellfyre** [comment]
Oh, I posted in the wrong project -.-
I'm sorry, I didn't realize that. Had a look at the omvextras issues and [instantly found the error](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-omvextrasorg) I'm seeing on my system. Apparently, their debian package doesn't support updates.

Thank you!

**Comment by ryecoaaron** [comment]
@hellfyre It does support updates now.  I just may have missed something.  Can you please open an issue?
