### ISSUE TITLE
Error when mounting two directories under a single btrfs subvolume

### ISSUE THREAD

**Issue by rlhelinski** [openmediavault/openmediavault#560]
### Description of issue

When creating a shared folder that is a sub-directory under a btrfs subvolume that is already shared, I get an error in the web UI.

The relevant problem seems to be:
```
          ID: restart_sharedfolder_oldhome_mount_unit
    Function: module.run
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 1933, in call
                  **cdata['kwargs'])
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 1951, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/utils/decorators/__init__.py", line 631, in _decorate
                  return self._call_function(kwargs)
                File "/usr/lib/python3/dist-packages/salt/utils/decorators/__init__.py", line 334, in _call_function
                  raise error
                File "/usr/lib/python3/dist-packages/salt/utils/decorators/__init__.py", line 321, in _call_function
                  return self._function(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/module.py", line 294, in run
                  func_args=kwargs.get(func))
                File "/usr/lib/python3/dist-packages/salt/states/module.py", line 358, in _call_function
                  mret = __salt__[name](*arg_type, **func_kw)
                File "/usr/lib/python3/dist-packages/salt/modules/systemd_service.py", line 906, in restart
                  raise CommandExecutionError(_strip_scope(ret['stderr']))
              salt.exceptions.CommandExecutionError: Job for sharedfolders-oldhome.mount failed.
              See "systemctl status sharedfolders-oldhome.mount" and "journalctl -xe" for details.
     Started: 20:22:50.108535
    Duration: 13.014 ms
     Changes:
```

```
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-salt deploy run systemd 2>&1' with exit code '1': debian: ---------- ID: remove_sharedfolder_mount_unit_files Function: module.run Result: True Comment: file.find: ['/etc/systemd/system/sharedfolders-boxy\\x2dapps.mount', '/etc/systemd/system/sharedfolders-oldhome.mount', '/etc/systemd/system/sharedfolders-home.mount', '/etc/systemd/system/sharedfolders-odroidhc2.mount', '/etc/systemd/system/sharedfolders-photos.mount', '/etc/systemd/system/sharedfolders-tmp.mount'] Started: 20:22:49.929790 Duration: 1.551 ms Changes: ---------- file.find: - /etc/systemd/system/sharedfolders-boxy\x2dapps.mount - /etc/systemd/system/sharedfolders-oldhome.mount - /etc/systemd/system/sharedfolders-home.mount - /etc/systemd/system/sharedfolders-odroidhc2.mount - /etc/systemd/system/sharedfolders-photos.mount - /etc/systemd/system/sharedfolders-tmp.mount ---------- ID: configure_sharedfolder_oldhome_mount_unit_file Function: file.managed Name: /etc/systemd/system/sharedfolders-oldhome.mount Result: True Comment: File /etc/systemd/system/sharedfolders-oldhome.mount updated Started: 20:22:49.932321 Duration: 1.605 ms Changes: ---------- diff: New file mode: 0644 ---------- ID: configure_sharedfolder_odroidhc2_mount_unit_file Function: file.managed Name: /etc/systemd/system/sharedfolders-odroidhc2.mount Result: True Comment: File /etc/systemd/system/sharedfolders-odroidhc2.mount updated Started: 20:22:49.933986 Duration: 1.091 ms Changes: ---------- diff: New file mode: 0644 ---------- ID: configure_sharedfolder_tmp_mount_unit_file Function: file.managed Name: /etc/systemd/system/sharedfolders-tmp.mount Result: True Comment: File /etc/systemd/system/sharedfolders-tmp.mount updated Started: 20:22:49.935134 Duration: 1.035 ms Changes: ---------- diff: New file mode: 0644 ---------- ID: configure_sharedfolder_home_mount_unit_file Function: file.managed Name: /etc/systemd/system/sharedfolders-home.mount Result: True Comment: File /etc/systemd/system/sharedfolders-home.mount updated Started: 20:22:49.936224 Duration: 1.035 ms Changes: ---------- diff: New file mode: 0644 ---------- ID: configure_sharedfolder_boxy-apps_mount_unit_file Function: file.managed Name: /etc/systemd/system/sharedfolders-boxy\x2dapps.mount Result: True Comment: File /etc/systemd/system/sharedfolders-boxy\x2dapps.mount updated Started: 20:22:49.937318 Duration: 1.035 ms Changes: ---------- diff: New file mode: 0644 ---------- ID: configure_sharedfolder_games_mount_unit_file Function: file.managed Name: /etc/systemd/system/sharedfolders-games.mount Result: True Comment: File /etc/systemd/system/sharedfolders-games.mount updated Started: 20:22:49.938408 Duration: 1.057 ms Changes: ---------- diff: New file mode: 0644 ---------- ID: sharedfolder_mount_units_systemctl_daemon_reload Function: module.run Name: service.systemctl_reload Result: True Comment: Started: 20:22:49.939522 Duration: 0.175 ms Changes: ---------- ID: enable_sharedfolder_oldhome_mount_unit Function: service.enabled Name: sharedfolders-oldhome.mount Result: True Comment: Service sharedfolders-oldhome.mount is already enabled, and is in the desired state Started: 20:22:49.943866 Duration: 164.512 ms Changes: ---------- ID: restart_sharedfolder_oldhome_mount_unit Function: module.run Result: False Comment: An exception occurred in this state: Traceback (most recent call last): File "/usr/lib/python3/dist-packages/salt/state.py", line 1933, in call **cdata['kwargs']) File "/usr/lib/python3/dist-packages/salt/loader.py", line 1951, in wrapper return f(*args, **kwargs) File "/usr/lib/python3/dist-packages/salt/utils/decorators/__init__.py", line 631, in _decorate return self._call_function(kwargs) File "/usr/lib/python3/dist-packages/salt/utils/decorators/__init__.py", line 334, in _call_function raise error File "/usr/lib/python3/dist-packages/salt/utils/decorators/__init__.py", line 321, in _call_function return self._function(*args, **kwargs) File "/usr/lib/python3/dist-packages/salt/states/module.py", line 294, in run func_args=kwargs.get(func)) File "/usr/lib/python3/dist-packages/salt/states/module.py", line 358, in _call_function mret = __salt__[name](*arg_type, **func_kw) File "/usr/lib/python3/dist-packages/salt/modules/systemd_service.py", line 906, in restart raise CommandExecutionError(_strip_scope(ret['stderr'])) salt.exceptions.CommandExecutionError: Job for sharedfolders-oldhome.mount failed. See "systemctl status sharedfolders-oldhome.mount" and "journalctl -xe" for details. Started: 20:22:50.108535 Duration: 13.014 ms Changes: ---------- ID: enable_sharedfolder_odroidhc2_mount_unit Function: service.enabled Name: sharedfolders-odroidhc2.mount Result: True Comment: Service sharedfolders-odroidhc2.mount is already enabled, and is in the desired state Started: 20:22:50.121714 Duration: 9.017 ms Changes: ---------- ID: restart_sharedfolder_odroidhc2_mount_unit Function: module.run Result: True Comment: service.restart: True Started: 20:22:50.130910 Duration: 19.566 ms Changes: ---------- service.restart: True ---------- ID: enable_sharedfolder_tmp_mount_unit Function: service.enabled Name: sharedfolders-tmp.mount Result: True Comment: Service sharedfolders-tmp.mount is already enabled, and is in the desired state Started: 20:22:50.150630 Duration: 9.326 ms Changes: ---------- ID: restart_sharedfolder_tmp_mount_unit Function: module.run Result: True Comment: service.restart: True Started: 20:22:50.160115 Duration: 19.312 ms Changes: ---------- service.restart: True ---------- ID: enable_sharedfolder_home_mount_unit Function: service.enabled Name: sharedfolders-home.mount Result: True Comment: Service sharedfolders-home.mount is already enabled, and is in the desired state Started: 20:22:50.179583 Duration: 9.942 ms Changes: ---------- ID: restart_sharedfolder_home_mount_unit Function: module.run Result: True Comment: service.restart: True Started: 20:22:50.189684 Duration: 19.728 ms Changes: ---------- service.restart: True ---------- ID: enable_sharedfolder_boxy-apps_mount_unit Function: service.enabled Name: sharedfolders-boxy\x2dapps.mount Result: True Comment: Service sharedfolders-boxy\x2dapps.mount is already enabled, and is in the desired state Started: 20:22:50.209568 Duration: 9.216 ms Changes: ---------- ID: restart_sharedfolder_boxy-apps_mount_unit Function: module.run Result: True Comment: service.restart: True Started: 20:22:50.218943 Duration: 19.42 ms Changes: ---------- service.restart: True ---------- ID: enable_sharedfolder_games_mount_unit Function: service.enabled Name: sharedfolders-games.mount Result: True Comment: Service sharedfolders-games.mount has been enabled, and is in the desired state Started: 20:22:50.238521 Duration: 140.523 ms Changes: ---------- sharedfolders-games.mount: True ---------- ID: restart_sharedfolder_games_mount_unit Function: module.run Result: True Comment: service.restart: True Started: 20:22:50.379200 Duration: 14.9 ms Changes: ---------- service.restart: True ---------- ID: configure_tmp_mount_unit_file Function: file.managed Name: /etc/systemd/system/tmp.mount Result: True Comment: File /etc/systemd/system/tmp.mount is in the correct state Started: 20:22:50.394252 Duration: 11.334 ms Changes: ---------- ID: tmp_mount_unit_systemctl_daemon_reload Function: module.run Name: service.systemctl_reload Result: True Comment: State was not run because none of the onchanges reqs changed Started: 20:22:50.405913 Duration: 0.002 ms Changes: Summary for debian ------------- Succeeded: 21 (changed=13) Failed: 1 ------------- Total states run: 22 Total run time: 468.396 ms/usr/lib/python3/dist-packages/salt/modules/file.py:32: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working from collections import Iterable, Mapping, namedtuple 
```

With the details:
``` 
Error #0:
OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-salt deploy run systemd 2>&1' with exit code '1': debian:
----------
          ID: remove_sharedfolder_mount_unit_files
    Function: module.run
      Result: True
     Comment: file.find: ['/etc/systemd/system/sharedfolders-boxy\\x2dapps.mount', '/etc/systemd/system/sharedfolders-oldhome.mount', '/etc/systemd/system/sharedfolders-home.mount', '/etc/systemd/system/sharedfolders-odroidhc2.mount', '/etc/systemd/system/sharedfolders-photos.mount', '/etc/systemd/system/sharedfolders-tmp.mount']
     Started: 20:22:49.929790
    Duration: 1.551 ms
     Changes:
              ----------
              file.find:
                  - /etc/systemd/system/sharedfolders-boxy\x2dapps.mount
                  - /etc/systemd/system/sharedfolders-oldhome.mount
                  - /etc/systemd/system/sharedfolders-home.mount
                  - /etc/systemd/system/sharedfolders-odroidhc2.mount
                  - /etc/systemd/system/sharedfolders-photos.mount
                  - /etc/systemd/system/sharedfolders-tmp.mount
----------
          ID: configure_sharedfolder_oldhome_mount_unit_file
    Function: file.managed
        Name: /etc/systemd/system/sharedfolders-oldhome.mount
      Result: True
     Comment: File /etc/systemd/system/sharedfolders-oldhome.mount updated
     Started: 20:22:49.932321
    Duration: 1.605 ms
     Changes:
              ----------
              diff:
                  New file
              mode:
                  0644
----------
          ID: configure_sharedfolder_odroidhc2_mount_unit_file
    Function: file.managed
        Name: /etc/systemd/system/sharedfolders-odroidhc2.mount
      Result: True
     Comment: File /etc/systemd/system/sharedfolders-odroidhc2.mount updated
     Started: 20:22:49.933986
    Duration: 1.091 ms
     Changes:
              ----------
              diff:
                  New file
              mode:
                  0644
----------
          ID: configure_sharedfolder_tmp_mount_unit_file
    Function: file.managed
        Name: /etc/systemd/system/sharedfolders-tmp.mount
      Result: True
     Comment: File /etc/systemd/system/sharedfolders-tmp.mount updated
     Started: 20:22:49.935134
    Duration: 1.035 ms
     Changes:
              ----------
              diff:
                  New file
              mode:
                  0644
----------
          ID: configure_sharedfolder_home_mount_unit_file
    Function: file.managed
        Name: /etc/systemd/system/sharedfolders-home.mount
      Result: True
     Comment: File /etc/systemd/system/sharedfolders-home.mount updated
     Started: 20:22:49.936224
    Duration: 1.035 ms
     Changes:
              ----------
              diff:
                  New file
              mode:
                  0644
----------
          ID: configure_sharedfolder_boxy-apps_mount_unit_file
    Function: file.managed
        Name: /etc/systemd/system/sharedfolders-boxy\x2dapps.mount
      Result: True
     Comment: File /etc/systemd/system/sharedfolders-boxy\x2dapps.mount updated
     Started: 20:22:49.937318
    Duration: 1.035 ms
     Changes:
              ----------
              diff:
                  New file
              mode:
                  0644
----------
          ID: configure_sharedfolder_games_mount_unit_file
    Function: file.managed
        Name: /etc/systemd/system/sharedfolders-games.mount
      Result: True
     Comment: File /etc/systemd/system/sharedfolders-games.mount updated
     Started: 20:22:49.938408
    Duration: 1.057 ms
     Changes:
              ----------
              diff:
                  New file
              mode:
                  0644
----------
          ID: sharedfolder_mount_units_systemctl_daemon_reload
    Function: module.run
        Name: service.systemctl_reload
      Result: True
     Comment:
     Started: 20:22:49.939522
    Duration: 0.175 ms
     Changes:
----------
          ID: enable_sharedfolder_oldhome_mount_unit
    Function: service.enabled
        Name: sharedfolders-oldhome.mount
      Result: True
     Comment: Service sharedfolders-oldhome.mount is already enabled, and is in the desired state
     Started: 20:22:49.943866
    Duration: 164.512 ms
     Changes:
----------
          ID: restart_sharedfolder_oldhome_mount_unit
    Function: module.run
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 1933, in call
                  **cdata['kwargs'])
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 1951, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/utils/decorators/__init__.py", line 631, in _decorate
                  return self._call_function(kwargs)
                File "/usr/lib/python3/dist-packages/salt/utils/decorators/__init__.py", line 334, in _call_function
                  raise error
                File "/usr/lib/python3/dist-packages/salt/utils/decorators/__init__.py", line 321, in _call_function
                  return self._function(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/module.py", line 294, in run
                  func_args=kwargs.get(func))
                File "/usr/lib/python3/dist-packages/salt/states/module.py", line 358, in _call_function
                  mret = __salt__[name](*arg_type, **func_kw)
                File "/usr/lib/python3/dist-packages/salt/modules/systemd_service.py", line 906, in restart
                  raise CommandExecutionError(_strip_scope(ret['stderr']))
              salt.exceptions.CommandExecutionError: Job for sharedfolders-oldhome.mount failed.
              See "systemctl status sharedfolders-oldhome.mount" and "journalctl -xe" for details.
     Started: 20:22:50.108535
    Duration: 13.014 ms
     Changes:
----------
          ID: enable_sharedfolder_odroidhc2_mount_unit
    Function: service.enabled
        Name: sharedfolders-odroidhc2.mount
      Result: True
     Comment: Service sharedfolders-odroidhc2.mount is already enabled, and is in the desired state
     Started: 20:22:50.121714
    Duration: 9.017 ms
     Changes:
----------
          ID: restart_sharedfolder_odroidhc2_mount_unit
    Function: module.run
      Result: True
     Comment: service.restart: True
     Started: 20:22:50.130910
    Duration: 19.566 ms
     Changes:
              ----------
              service.restart:
                  True
----------
          ID: enable_sharedfolder_tmp_mount_unit
    Function: service.enabled
        Name: sharedfolders-tmp.mount
      Result: True
     Comment: Service sharedfolders-tmp.mount is already enabled, and is in the desired state
     Started: 20:22:50.150630
    Duration: 9.326 ms
     Changes:
----------
          ID: restart_sharedfolder_tmp_mount_unit
    Function: module.run
      Result: True
     Comment: service.restart: True
     Started: 20:22:50.160115
    Duration: 19.312 ms
     Changes:
              ----------
              service.restart:
                  True
----------
          ID: enable_sharedfolder_home_mount_unit
    Function: service.enabled
        Name: sharedfolders-home.mount
      Result: True
     Comment: Service sharedfolders-home.mount is already enabled, and is in the desired state
     Started: 20:22:50.179583
    Duration: 9.942 ms
     Changes:
----------
          ID: restart_sharedfolder_home_mount_unit
    Function: module.run
      Result: True
     Comment: service.restart: True
     Started: 20:22:50.189684
    Duration: 19.728 ms
     Changes:
              ----------
              service.restart:
                  True
----------
          ID: enable_sharedfolder_boxy-apps_mount_unit
    Function: service.enabled
        Name: sharedfolders-boxy\x2dapps.mount
      Result: True
     Comment: Service sharedfolders-boxy\x2dapps.mount is already enabled, and is in the desired state
     Started: 20:22:50.209568
    Duration: 9.216 ms
     Changes:
----------
          ID: restart_sharedfolder_boxy-apps_mount_unit
    Function: module.run
      Result: True
     Comment: service.restart: True
     Started: 20:22:50.218943
    Duration: 19.42 ms
     Changes:
              ----------
              service.restart:
                  True
----------
          ID: enable_sharedfolder_games_mount_unit
    Function: service.enabled
        Name: sharedfolders-games.mount
      Result: True
     Comment: Service sharedfolders-games.mount has been enabled, and is in the desired state
     Started: 20:22:50.238521
    Duration: 140.523 ms
     Changes:
              ----------
              sharedfolders-games.mount:
                  True
----------
          ID: restart_sharedfolder_games_mount_unit
    Function: module.run
      Result: True
     Comment: service.restart: True
     Started: 20:22:50.379200
    Duration: 14.9 ms
     Changes:
              ----------
              service.restart:
                  True
----------
          ID: configure_tmp_mount_unit_file
    Function: file.managed
        Name: /etc/systemd/system/tmp.mount
      Result: True
     Comment: File /etc/systemd/system/tmp.mount is in the correct state
     Started: 20:22:50.394252
    Duration: 11.334 ms
     Changes:
----------
          ID: tmp_mount_unit_systemctl_daemon_reload
    Function: module.run
        Name: service.systemctl_reload
      Result: True
     Comment: State was not run because none of the onchanges reqs changed
     Started: 20:22:50.405913
    Duration: 0.002 ms
     Changes:

Summary for debian
-------------
Succeeded: 21 (changed=13)
Failed:     1
-------------
Total states run:     22
Total run time:  468.396 ms/usr/lib/python3/dist-packages/salt/modules/file.py:32: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Iterable, Mapping, namedtuple
 in /usr/share/php/openmediavault/system/process.inc:182
Stack trace:
#0 /usr/share/php/openmediavault/engine/module/serviceabstract.inc(60): OMV\System\Process->execute()
#1 /usr/share/openmediavault/engined/rpc/config.inc(167): OMV\Engine\Module\ServiceAbstract->deploy()
#2 [internal function]: Engined\Rpc\Config->applyChanges(Array, Array)
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#4 /usr/share/php/openmediavault/rpc/serviceabstract.inc(149): OMV\Rpc\ServiceAbstract->callMethod('applyChanges', Array, Array)
#5 /usr/share/php/openmediavault/rpc/serviceabstract.inc(588): OMV\Rpc\ServiceAbstract->OMV\Rpc\{closure}('/tmp/bgstatusJh...', '/tmp/bgoutput2S...')
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(159): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure))
#7 /usr/share/openmediavault/engined/rpc/config.inc(189): OMV\Rpc\ServiceAbstract->callMethodBg('applyChanges', Array, Array)
#8 [internal function]: Engined\Rpc\Config->applyChangesBg(Array, Array)
#9 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#10 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('applyChangesBg', Array, Array)
#11 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('Config', 'applyChangesBg', Array, Array, 1)
#12 {main}
```

### Steps to reproduce issue
(Include debug logs if possible and relevant.)

**Comment by rlhelinski** [comment]
Sorry, I could not seem to edit the text after posting or add labels. This is OpenMediaVault 5.2.2, but I also saw the issue with 5.2.1.

**Comment by mi-hol** [comment]
@rlhelinski is this still open?

**Comment by rlhelinski** [comment]
I do not think I was able to circumvent this issue, but I have since migrated my filesystem to ZFS (because of recurring kernel crashes after using `bees`). I am fine with closing.
