### ISSUE TITLE
Invalid RPC response.

### ISSUE THREAD

**Issue by Dude234** [openmediavault/openmediavault#583]
### Description of issue/question
the inclusion of the data pool (unionfilesystem) is not possible

### Steps to reproduce issue
After setting up the Snapraid network I set up the unionfilesystem "data pool".
When I select the desired target under CIFS and choose the data pool for sharing, I get the mentioned error.

```
Error #0: 
OMV\Rpc\Exception: Invalid RPC response. Please check the syslog for more information. in /usr/share/php/openmediavault/rpc/rpc.inc:187
Stack trace:
#0 /usr/share/php/openmediavault/rpc/proxy/json.inc(97): OMV\Rpc\Rpc::call('ShareMgmt', 'getCandidates', Array, Array, 3)
#1 /var/www/openmediavault/rpc.php(45): OMV\Rpc\Proxy\Json->handle()
#2 {main}
```

```
Feb  1 15:47:36 openmediavault5 omv-engined[1753]: PHP Fatal error: Uncaught Error: Call to a member function getImpl() on null in /usr/share/php/openmediavault/system/filesystem/filesystem.inc:898
Feb  1 15:47:36 openmediavault5 omv-engined[1753]: Stack trace:
Feb  1 15:47:36 openmediavault5 omv-engined[1753]: #0 /usr/share/openmediavault/engined/rpc/sharemgmt.inc(88): OMV\System\Filesystem\Filesystem::getImplByMountPoint('/srv/5accee2a-9...')
Feb  1 15:47:36 openmediavault5 omv-engined[1753]: #1 [internal function]: Engined\Rpc\ShareMgmt->getCandidates(Array, Array)
Feb  1 15:47:36 openmediavault5 omv-engined[1753]: #2 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
Feb  1 15:47:36 openmediavault5 omv-engined[1753]: #3 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('getCandidates', Array, Array)
Feb  1 15:47:36 openmediavault5 omv-engined[1753]: #4 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('ShareMgmt', 'getCandidates', Array, Array, 1)
Feb  1 15:47:36 openmediavault5 omv-engined[1753]: #5 {main}
Feb  1 15:47:36 openmediavault5 omv-engined[1753]:   thrown in /usr/share/php/openmediavault/system/filesystem/filesystem.inc on line 898
```

### Versions report
Version: 5.2.6-1 (Usul)
Kernel: 5.4.0.0.bpo.2-amd64
Snapraid 5.0.5
unionfilesystem 5.1

**Comment by ryecoaaron** [comment]
This was caused by this change in 5.2.6 - https://github.com/openmediavault/openmediavault/commit/bd2c6961dee5d818cac8b8d540f6a9dbf84984f7

**Comment by Helly1206** [comment]
It seems that all filesystems that do not refer to /dev/xxxx cause this issue. I made a workaround to search the fs by type if the backend cannot be detected. I created a pull request.

**Comment by rlhelinski** [comment]
Same issue here.

**Comment by votdev** [comment]
What is the output of `findmnt --first-only --noheadings --raw --output=FSTYPE /srv/5accee2a-9...`? Please use the correct mount path of your mergerfs volume. It's truncated in the error trace.

**Comment by rlhelinski** [comment]
In the web GUI, I get
```
Error #0:
OMV\Rpc\Exception: Invalid RPC response. Please check the syslog for more information. in /usr/share/php/openmediavault/rpc/rpc.inc:187
Stack trace:
#0 /usr/share/php/openmediavault/rpc/proxy/json.inc(97): OMV\Rpc\Rpc::call('ShareMgmt', 'enumerateShared...', Array, Array, 3)
#1 /var/www/openmediavault/rpc.php(45): OMV\Rpc\Proxy\Json->handle()
#2 {main}
```
In `/var/log/syslog`, I see
```
Feb  3 08:05:02 boxy omv-engined[27282]: PHP Fatal error: Uncaught Error: Call to a member function getImpl() on null in /usr/share/php/openmediavault/system/filesystem/filesystem.inc:898
Feb  3 08:05:02 boxy omv-engined[27282]: Stack trace:
Feb  3 08:05:02 boxy omv-engined[27282]: #0 /usr/share/openmediavault/engined/rpc/sharemgmt.inc(158): OMV\System\Filesystem\Filesystem::getImplByMountPoint('/srv/dev-disk-b...')
Feb  3 08:05:02 boxy omv-engined[27282]: #1 [internal function]: Engined\Rpc\ShareMgmt->enumerateSharedFolders(Array, Array)
Feb  3 08:05:02 boxy omv-engined[27282]: #2 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
Feb  3 08:05:02 boxy omv-engined[27282]: #3 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('enumerateShared...', Array, Array)
Feb  3 08:05:02 boxy omv-engined[27282]: #4 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('ShareMgmt', 'enumerateShared...', Array, Array, 1)
Feb  3 08:05:02 boxy omv-engined[27282]: #5 {main}
Feb  3 08:05:02 boxy omv-engined[27282]:   thrown in /usr/share/php/openmediavault/system/filesystem/filesystem.inc on line 898
```

The output of the command is `btrfs`:
```
ryan@boxy:~$ findmnt --first-only --noheadings --raw --output=FSTYPE /srv/dev-disk-by-label-sphere 
btrfs
```
