### ISSUE TITLE
Error when applying NUT settings

### ISSUE THREAD

**Issue by lldsolitude** [openmediavault/openmediavault#666]
### Description of issue/question
The following error occurs when applying NUT settings.
```
----------
          ID: monitor_nut_server_service
    Function: monit.monitor
        Name: nut-server
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 1933, in call
                  **cdata['kwargs'])
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 1951, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/monit.py", line 48, in monitor
                  if 'Running' in value[name]:
              TypeError: string indices must be integers
     Started: 19:51:51.201868
    Duration: 20.81 ms
     Changes:
----------
          ID: monitor_nut_monitor_service
    Function: monit.monitor
        Name: nut-monitor
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 1933, in call
                  **cdata['kwargs'])
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 1951, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/monit.py", line 48, in monitor
                  if 'Running' in value[name]:
              TypeError: string indices must be integers
     Started: 19:51:51.223093
    Duration: 15.528 ms
     Changes:
```
### Versions report
omv 5.3.9
openmediavault-nut 5.0.3

**Comment by lldsolitude** [comment]
Somehow reinstalling nut plugin solved the problem. Closing.

**Comment by 1994rstefan** [comment]
I am getting the exact same error message using omv 5.5.1 and openmediavault-nut 5.1.0. Unfortunately reinstalling NUT plugin did not help.

**Comment by votdev** [comment]
I think the problem is a not running monit process. Can you confirm that? `systemctl status monit`.

**Comment by 1994rstefan** [comment]
@votdev thank you, that was the problem.
I upgraded from Debian 9 which had not merged the /usr folder. So the first time the monit config was invalid and the service did not restart. Problem solved :+1:
