### ISSUE TITLE
OMV fails to generate collectd configuration

### ISSUE THREAD

**Issue by dguihal** [openmediavault/openmediavault#673]
# Description of issue/question

Failure generation collectd config with omv5

### Steps to reproduce issue
(Include debug logs if possible and relevant.)

```bash
omv-salt deploy run collectd

xxxx.yyyyy:
    Data failed to compile:
----------
    Rendering SLS 'base:omv.deploy.collectd.plugins.interface' failed: Jinja error: Failed to convert property 'mtu': invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/openmediavault/config/datamodel.py", line 290, in property_convert
    result = int(value)
ValueError: invalid literal for int() with base 10: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 394, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 21, in top-level template code
  File "/var/cache/salt/minion/extmods/modules/omv_conf.py", line 82, in get_by_filter
    objs = db.get_by_filter(id_, openmediavault.config.DatabaseFilter(filter_), **kwargs)
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 125, in get_by_filter
    query.execute()
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 683, in execute
    self._response = self._elements_to_object(elements)
  File "/usr/lib/python3/dist-packages/openmediavault/config/database.py", line 467, in _elements_to_object
    obj.set_dict(self._element_to_dict(element), False)
  File "/usr/lib/python3/dist-packages/openmediavault/config/object.py", line 207, in set_dict
    self.set(key, value, validate)
  File "/usr/lib/python3/dist-packages/openmediavault/config/object.py", line 185, in set
    value = self.model.property_convert(name, value)
  File "/usr/lib/python3/dist-packages/openmediavault/config/datamodel.py", line 300, in property_convert
    name, str(e)))
ValueError: Failed to convert property 'mtu': invalid literal for int() with base 10: ''

; line 21

---
[...]
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

{% set interfaces = [] %}
{% for interface in salt['omv_conf.get_by_filter'](    <======================
  'conf.system.network.interface',
  {'operator': 'or', 'arg0': {'operator': 'stringEquals', 'arg0': 'type', 'arg1': 'ethernet'}, 'arg1': {'operator': 'stringEquals', 'arg0': 'type', 'arg1': 'wireless'}}) %}
{% set used_by = salt['omv_conf.get_by_filter'](
  'conf.system.network.interface',
  {'operator': 'stringContains', 'arg0': 'slaves', 'arg1': interface.devicename}) %}
[...]
---
```

### Versions report

```bash
dpkg -l |grep openmediavault
ii  openmediavault                       5.3.9-1                             all          openmediavault - The open network attached storage solution
ii  openmediavault-backup                5.2                                 all          backup plugin for OpenMediaVault.
ii  openmediavault-keyring               1.0                                 all          GnuPG archive keys of the OpenMediaVault archive
ii  openmediavault-lvm2                  5.0.2-1                             all          openmediavault Logical Volume Manager (LVM2) plugin
ii  openmediavault-omvextrasorg          5.2.6                               all          OMV-Extras.org Package Repositories for OpenMediaVault
```

```bash
ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether d0:50:99:15:66:38 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.5/24 brd 192.168.1.255 scope global eth0
       valid_lft forever preferred_lft forever
3: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:e6:60:e9:71 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
5: veth86d7d38@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default 
    link/ether 9e:ce:d2:37:d8:7f brd ff:ff:ff:ff:ff:ff link-netnsid 0
```

**Comment by dguihal** [comment]
Seetings MTU to 1500 in the OMV UI seems to have fixed the issue

**Comment by votdev** [comment]
Was this system migrated from OMV4 or have you modified the database manually? It is not possible that this is done by the system because the database REQUIRES the `mtu` field to be set when this is [modified via RPC](https://github.com/openmediavault/openmediavault/blob/master/deb/openmediavault/usr/share/openmediavault/datamodels/rpc.network.json#L62).

**Comment by votdev** [comment]
I close this because technically it is not possible that this behavior was introduced by OMV.
