### ISSUE TITLE
Cannot set hostname

### ISSUE THREAD

**Issue by fcimeson** [openmediavault/openmediavault#739]
### Description of issue/question
When trying to apply the new configuration, an error pops up indicating that the hostname could not be set.

### Steps to reproduce issue
* Change Hostname
* Wait for apply message
* Apply
* Wait
* Get error message

### Versions report
* Rasbian Buster Lite
* openmediavault-backup/buster,now 5.2 all [installed]
* openmediavault-diskstats/usul,usul,now 5.0.5-1 all [installed]
* openmediavault-keyring/usul,usul,now 1.0 all [installed]
* openmediavault-omvextrasorg/buster,now 5.3.3 all [installed]
* openmediavault-unionfilesystems/buster,now 5.1.2 all [installed]
* openmediavault/usul,usul,now 5.5.2-1 all [installed]

```
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-salt deploy run systemd-networkd 2>&1' with exit code '1': raspberrypi: ---------- ID: configure_etc_network_interfaces Function: file.managed Name: /etc/network/interfaces Result: True Comment: File /etc/network/interfaces is in the correct state Started: 07:12:50.339663 Duration: 66.957 ms Changes: ---------- ID: remove_systemd_networkd_config_files Function: module.run Result: True Comment: file.find: [] Started: 07:12:50.408137 Duration: 3.104 ms Changes: ---------- file.find: ---------- ID: remove_empty_systemd_networkd_config_files Function: module.run Result: True Comment: file.find: [] Started: 07:12:50.411544 Duration: 1.802 ms Changes: ---------- file.find: ---------- ID: remove_netplan_config_files Function: module.run Result: True Comment: file.find: ['/etc/netplan/10-openmediavault-default.yaml'] Started: 07:12:50.413622 Duration: 2.532 ms Changes: ---------- file.find: - /etc/netplan/10-openmediavault-default.yaml ---------- ID: configure_netplan_default Function: file.managed Name: /etc/netplan/10-openmediavault-default.yaml Result: True Comment: File /etc/netplan/10-openmediavault-default.yaml updated Started: 07:12:50.416454 Duration: 20.654 ms Changes: ---------- diff: New file mode: 0644 ---------- ID: apply_netplan_config Function: cmd.run Name: netplan apply Result: False Comment: Command "netplan apply" run Started: 07:12:50.438854 Duration: 318.695 ms Changes: ---------- pid: 2140 retcode: 1 stderr: Traceback (most recent call last): File "/usr/sbin/netplan", line 23, in <module> netplan.main() File "/usr/share/netplan/netplan/cli/core.py", line 50, in main self.run_command() File "/usr/share/netplan/netplan/cli/utils.py", line 130, in run_command self.func() File "/usr/share/netplan/netplan/cli/commands/apply.py", line 43, in run self.run_command() File "/usr/share/netplan/netplan/cli/utils.py", line 130, in run_command self.func() File "/usr/share/netplan/netplan/cli/commands/apply.py", line 93, in command_apply stderr=subprocess.DEVNULL) File "/usr/lib/python3.7/subprocess.py", line 347, in check_call raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command '['udevadm', 'test-builtin', 'net_setup_link', '/sys/class/net/lo']' returned non-zero exit status 1. stdout: Summary for raspberrypi ------------ Succeeded: 5 (changed=5) Failed: 1 ------------ Total states run: 6 Total run time: 413.744 ms
```

**Comment by fcimeson** [comment]
Here is another occurrence of what looks to be a related issue.

```
{'response': None, 'error': {'code': 0, 'message': 'Failed to execute command \'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-salt deploy run systemd-networkd 2>&1\' with exit code \'1\': raspberrypi:\n----------\n          ID: configure_etc_network_interfaces\n    Function: file.managed\n        Name: /etc/network/interfaces\n      Result: True\n     Comment: File /etc/network/interfaces is in the correct state\n     Started: 19:56:11.603357\n    Duration: 61.956 ms\n     Changes:\n----------\n          ID: remove_systemd_networkd_config_files\n    Function: module.run\n      Result: True\n     Comment: file.find: []\n     Started: 19:56:11.666870\n    Duration: 3.072 ms\n     Changes:\n              ----------\n              file.find:\n----------\n          ID: remove_empty_systemd_networkd_config_files\n    Function: module.run\n      Result: True\n     Comment: file.find: []\n     Started: 19:56:11.670243\n    Duration: 1.804 ms\n     Changes:\n              ----------\n              file.find:\n----------\n          ID: remove_netplan_config_files\n    Function: module.run\n      Result: True\n     Comment: file.find: [\'/etc/netplan/10-openmediavault-default.yaml\', \'/etc/netplan/30-openmediavault-wlan0.yaml\']\n     Started: 19:56:11.672324\n    Duration: 2.576 ms\n     Changes:\n              ----------\n              file.find:\n                  - /etc/netplan/10-openmediavault-default.yaml\n                  - /etc/netplan/30-openmediavault-wlan0.yaml\n----------\n          ID: configure_netplan_default\n    Function: file.managed\n        Name: /etc/netplan/10-openmediavault-default.yaml\n      Result: True\n     Comment: File /etc/netplan/10-openmediavault-default.yaml updated\n     Started: 19:56:11.675201\n    Duration: 16.343 ms\n     Changes:\n              ----------\n              diff:\n                  New file\n              mode:\n                  0644\n----------\n          ID: configure_netplan_ethernet_eth0\n    Function: file.managed\n        Name: /etc/netplan/20-openmediavault-eth0.yaml\n      Result: True\n     Comment: File /etc/netplan/20-openmediavault-eth0.yaml updated\n     Started: 19:56:11.691879\n    Duration: 66.085 ms\n     Changes:\n              ----------\n              diff:\n                  New file\n              mode:\n                  0644\n----------\n          ID: apply_netplan_config\n    Function: cmd.run\n        Name: netplan apply\n      Result: False\n     Comment: Command "netplan apply" run\n     Started: 19:56:11.759646\n    Duration: 292.914 ms\n     Changes:\n              ----------\n              pid:\n                  32126\n              retcode:\n                  1\n              stderr:\n                  Traceback (most recent call last):\n                    File "/usr/sbin/netplan", line 23, in <module>\n                      netplan.main()\n                    File "/usr/share/netplan/netplan/cli/core.py", line 50, in main\n                      self.run_command()\n                    File "/usr/share/netplan/netplan/cli/utils.py", line 130, in run_command\n                      self.func()\n                    File "/usr/share/netplan/netplan/cli/commands/apply.py", line 43, in run\n                      self.run_command()\n                    File "/usr/share/netplan/netplan/cli/utils.py", line 130, in run_command\n                      self.func()\n                    File "/usr/share/netplan/netplan/cli/commands/apply.py", line 93, in command_apply\n                      stderr=subprocess.DEVNULL)\n                    File "/usr/lib/python3.7/subprocess.py", line 347, in check_call\n                      raise CalledProcessError(retcode, cmd)\n                  subprocess.CalledProcessError: Command \'[\'udevadm\', \'test-builtin\', \'net_setup_link\', \'/sys/class/net/lo\']\' returned non-zero exit status 1.\n              stdout:\n\nSummary for raspberrypi\n------------\nSucceeded: 6 (changed=6)\nFailed:    1\n------------\nTotal states run:     7\nTotal run time: 444.750 ms', 'trace': 'OMV\\ExecException: Failed to execute command \'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-salt deploy run systemd-networkd 2>&1\' with exit code \'1\': raspberrypi:\n----------\n          ID: configure_etc_network_interfaces\n    Function: file.managed\n        Name: /etc/network/interfaces\n      Result: True\n     Comment: File /etc/network/interfaces is in the correct state\n     Started: 19:56:11.603357\n    Duration: 61.956 ms\n     Changes:\n----------\n          ID: remove_systemd_networkd_config_files\n    Function: module.run\n      Result: True\n     Comment: file.find: []\n     Started: 19:56:11.666870\n    Duration: 3.072 ms\n     Changes:\n              ----------\n              file.find:\n----------\n          ID: remove_empty_systemd_networkd_config_files\n    Function: module.run\n      Result: True\n     Comment: file.find: []\n     Started: 19:56:11.670243\n    Duration: 1.804 ms\n     Changes:\n              ----------\n              file.find:\n----------\n          ID: remove_netplan_config_files\n    Function: module.run\n      Result: True\n     Comment: file.find: [\'/etc/netplan/10-openmediavault-default.yaml\', \'/etc/netplan/30-openmediavault-wlan0.yaml\']\n     Started: 19:56:11.672324\n    Duration: 2.576 ms\n     Changes:\n              ----------\n              file.find:\n                  - /etc/netplan/10-openmediavault-default.yaml\n                  - /etc/netplan/30-openmediavault-wlan0.yaml\n----------\n          ID: configure_netplan_default\n    Function: file.managed\n        Name: /etc/netplan/10-openmediavault-default.yaml\n      Result: True\n     Comment: File /etc/netplan/10-openmediavault-default.yaml updated\n     Started: 19:56:11.675201\n    Duration: 16.343 ms\n     Changes:\n              ----------\n              diff:\n                  New file\n              mode:\n                  0644\n----------\n          ID: configure_netplan_ethernet_eth0\n    Function: file.managed\n        Name: /etc/netplan/20-openmediavault-eth0.yaml\n      Result: True\n     Comment: File /etc/netplan/20-openmediavault-eth0.yaml updated\n     Started: 19:56:11.691879\n    Duration: 66.085 ms\n     Changes:\n              ----------\n              diff:\n                  New file\n              mode:\n                  0644\n----------\n          ID: apply_netplan_config\n    Function: cmd.run\n        Name: netplan apply\n      Result: False\n     Comment: Command "netplan apply" run\n     Started: 19:56:11.759646\n    Duration: 292.914 ms\n     Changes:\n              ----------\n              pid:\n                  32126\n              retcode:\n                  1\n              stderr:\n                  Traceback (most recent call last):\n                    File "/usr/sbin/netplan", line 23, in <module>\n                      netplan.main()\n                    File "/usr/share/netplan/netplan/cli/core.py", line 50, in main\n                      self.run_command()\n                    File "/usr/share/netplan/netplan/cli/utils.py", line 130, in run_command\n                      self.func()\n                    File "/usr/share/netplan/netplan/cli/commands/apply.py", line 43, in run\n                      self.run_command()\n                    File "/usr/share/netplan/netplan/cli/utils.py", line 130, in run_command\n                      self.func()\n                    File "/usr/share/netplan/netplan/cli/commands/apply.py", line 93, in command_apply\n                      stderr=subprocess.DEVNULL)\n                    File "/usr/lib/python3.7/subprocess.py", line 347, in check_call\n                      raise CalledProcessError(retcode, cmd)\n                  subprocess.CalledProcessError: Command \'[\'udevadm\', \'test-builtin\', \'net_setup_link\', \'/sys/class/net/lo\']\' returned non-zero exit status 1.\n              stdout:\n\nSummary for raspberrypi\n------------\nSucceeded: 6 (changed=6)\nFailed:    1\n------------\nTotal states run:     7\nTotal run time: 444.750 ms in /usr/share/php/openmediavault/system/process.inc:182\nStack trace:\n#0 /usr/share/php/openmediavault/engine/module/serviceabstract.inc(60): OMV\\System\\Process->execute()\n#1 /usr/share/openmediavault/engined/rpc/config.inc(167): OMV\\Engine\\Module\\ServiceAbstract->deploy()\n#2 [internal function]: Engined\\Rpc\\Config->applyChanges(Array, Array)\n#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)\n#4 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\\Rpc\\ServiceAbstract->callMethod(\'applyChanges\', Array, Array)\n#5 /usr/sbin/omv-engined(537): OMV\\Rpc\\Rpc::call(\'Config\', \'applyChanges\', Array, Array, 1)\n#6 {main}', 'http_status_code': 500}}
ERROR: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-salt deploy run systemd-networkd 2>&1' with exit code '1': raspberrypi:
----------
          ID: configure_etc_network_interfaces
    Function: file.managed
        Name: /etc/network/interfaces
      Result: True
     Comment: File /etc/network/interfaces is in the correct state
     Started: 19:56:11.603357
    Duration: 61.956 ms
     Changes:
----------
          ID: remove_systemd_networkd_config_files
    Function: module.run
      Result: True
     Comment: file.find: []
     Started: 19:56:11.666870
    Duration: 3.072 ms
     Changes:
              ----------
              file.find:
----------
          ID: remove_empty_systemd_networkd_config_files
    Function: module.run
      Result: True
     Comment: file.find: []
     Started: 19:56:11.670243
    Duration: 1.804 ms
     Changes:
              ----------
              file.find:
----------
          ID: remove_netplan_config_files
    Function: module.run
      Result: True
     Comment: file.find: ['/etc/netplan/10-openmediavault-default.yaml', '/etc/netplan/30-openmediavault-wlan0.yaml']
     Started: 19:56:11.672324
    Duration: 2.576 ms
     Changes:
              ----------
              file.find:
                  - /etc/netplan/10-openmediavault-default.yaml
                  - /etc/netplan/30-openmediavault-wlan0.yaml
----------
          ID: configure_netplan_default
    Function: file.managed
        Name: /etc/netplan/10-openmediavault-default.yaml
      Result: True
     Comment: File /etc/netplan/10-openmediavault-default.yaml updated
     Started: 19:56:11.675201
    Duration: 16.343 ms
     Changes:
              ----------
              diff:
                  New file
              mode:
                  0644
----------
          ID: configure_netplan_ethernet_eth0
    Function: file.managed
        Name: /etc/netplan/20-openmediavault-eth0.yaml
      Result: True
     Comment: File /etc/netplan/20-openmediavault-eth0.yaml updated
     Started: 19:56:11.691879
    Duration: 66.085 ms
     Changes:
              ----------
              diff:
                  New file
              mode:
                  0644
----------
          ID: apply_netplan_config
    Function: cmd.run
        Name: netplan apply
      Result: False
     Comment: Command "netplan apply" run
     Started: 19:56:11.759646
    Duration: 292.914 ms
     Changes:
              ----------
              pid:
                  32126
              retcode:
                  1
              stderr:
                  Traceback (most recent call last):
                    File "/usr/sbin/netplan", line 23, in <module>
                      netplan.main()
                    File "/usr/share/netplan/netplan/cli/core.py", line 50, in main
                      self.run_command()
                    File "/usr/share/netplan/netplan/cli/utils.py", line 130, in run_command
                      self.func()
                    File "/usr/share/netplan/netplan/cli/commands/apply.py", line 43, in run
                      self.run_command()
                    File "/usr/share/netplan/netplan/cli/utils.py", line 130, in run_command
                      self.func()
                    File "/usr/share/netplan/netplan/cli/commands/apply.py", line 93, in command_apply
                      stderr=subprocess.DEVNULL)
                    File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
                      raise CalledProcessError(retcode, cmd)
                  subprocess.CalledProcessError: Command '['udevadm', 'test-builtin', 'net_setup_link', '/sys/class/net/lo']' returned non-zero exit status 1.
              stdout:

Summary for raspberrypi
------------
Succeeded: 6 (changed=6)
Failed:    1
------------
Total states run:     7
Total run time: 444.750 ms
```

**Comment by votdev** [comment]
This is a problem of the RPi image you're using. The problem is solved some time ago by the [installation script](https://github.com/OpenMediaVault-Plugin-Developers/installScript).

**Comment by fcimeson** [comment]
Nice, thanks. So I'm guessing I need a complete reinstall or would running the script with an existing omv install work?

**Comment by votdev** [comment]
> Nice, thanks. So I'm guessing I need a complete reinstall or would running the script with an existing omv install work?

You could try to fix it by removing the file `/etc/systemd/network/99-default.link`. If this does not work, then you should try a new installation.

**Comment by fcimeson** [comment]
I had a number of other issues so I just did a complete reinstall. OMV is working much much better. Thanks for your help.
