### ISSUE TITLE
"Invalid RPC response" in multiple places and other weird behavior

### ISSUE THREAD

**Issue by Jim-Lafleur** [openmediavault/openmediavault#742]
`OMV Version: Linux openmediavault 5.5.0-0.bpo.2-amd64 #1 SMP Debian 5.5.17-1~bpo10+1 (2020-04-23) x86_64 GNU/Linux`

I've got errors within the OMV web GUI. It happens in multiple places:

When I click : System: Date and Time:
```
Invalid RPC response. Please check the syslog for more information.
Error #0:OMV\Rpc\Exception: Invalid RPC response. Please check the syslog for more information. in /usr/share/php/openmediavault/rpc/rpc.inc:187 Stack trace: #0 /usr/share/php/openmediavault/rpc/proxy/json.inc(97): OMV\Rpc\Rpc::call('System', 'getTimeSettings', NULL, Array, 3) #1 /var/www/openmediavault/rpc.php(45): OMV\Rpc\Proxy\Json->handle() #2 {main}
```

When I click: Diagnostics: System Logs:
```
Invalid RPC response. Please check the syslog for more information.
Error #0:OMV\Rpc\Exception: Invalid RPC response. Please check the syslog for more information. in /usr/share/php/openmediavault/rpc/rpc.inc:187 Stack trace: #0 /usr/share/php/openmediavault/rpc/proxy/json.inc(97): OMV\Rpc\Rpc::call('LogFile', 'getList', Array, Array, 3) #1 /var/www/openmediavault/rpc.php(45): OMV\Rpc\Proxy\Json->handle() #2 {main}
```

If I click these, nothing happens (The GUI doesn't switch to those pages):
Diagnostics:
---Dashboard
---System Information

When I change any settings anywhere and click "Save", the system doesn't ask for confirmation like it usually do at the top in a yellow rectangle.
Image of what it doesn't do anymore:
![image](https://user-images.githubusercontent.com/21689981/85087596-464e7d00-b1b4-11ea-8825-0fc9f36673e6.png)

I did a shutdown and started back the machine. Still same errors.
This is a fresh install of OMV in a VM (VMWare). The only thing I did was messing a bit with DNS, but I've resoved it. It's working fine now.

Any ideas on how to fix this?

FYI:

```
root@openmediavault:~# php -version
PHP 7.3.14-1~deb10u1 (cli) (built: Feb 16 2020 15:07:23) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.14, Copyright (c) 1998-2018 Zend Technologies
with Zend OPcache v7.3.14-1~deb10u1, Copyright (c) 1999-2018, by Zend Technologies
```

**Comment by votdev** [comment]
To get more information and the reason for the failure please check the syslog as mentioned in the error message.

**Comment by Jim-Lafleur** [comment]
Hi Volker,

Here's the error in syslog: 
`Jun 19 01:07:21 openmediavault omv-engined[12070]: PHP Fatal error: strftime(): Timezone database is corrupt - this should *never* happen! in /usr/share/openmediavault/engined/rpc/system.inc on line 346`

**Comment by Jim-Lafleur** [comment]
OK. I've fixed it! 😄 
I'll write what I did in my next post.

**Comment by Jim-Lafleur** [comment]
While troubleshooting I noticed that the timezone file for my zone was corrupt: 
```
root@openmediavault:/usr/share/zoneinfo/America# ls
Adak            Belize         Chihuahua      Eirunepe     Guyana        La_Paz         Merida       North_Dakota    Rankin_Inlet   St_Barthelemy  Virgin
Anchorage       Blanc-Sablon   Coral_Harbour  El_Salvador  Halifax       Lima           Metlakatla   Nuuk            Recife         St_Johns       Whitehorse
Anguilla        Boa_Vista      Cordoba        Ensenada     Havana        Los_Angeles    Mexico_City  Ojinaga         Regina         St_Kitts       Winnipeg
Antigua         Bogota         Costa_Rica     Fortaleza    Hermosillo    Louisville     Miquelon     Panama          Resolute       St_Lucia       Yakutat
Araguaina       Boise          Creston        Fort_Nelson  Indiana       Lower_Princes  Moncton      Pangnirtung     Rio_Branco     St_Thomas      Yellowknife
Argentina       Buenos_Aires   Cuiaba         Fort_Wayne   Indianapolis  Maceio         Monterrey    Paramaribo      Rosario        St_Vincent
Aruba           Cambridge_Bay  Curacao        Glace_Bay    Inuvik        Managua        Montevideo   Phoenix         Santa_Isabel   Swift_Current
Asuncion        Campo_Grande   Danmarkshavn   Godthab      Iqaluit       Manaus         Montreal     Port-au-Prince  Santarem       Tegucigalpa
Atikokan        Cancun         Dawson         Goose_Bay    Jamaica       Marigot        Montserrat   Porto_Acre      Santiago       Thule
Atka            Caracas        Dawson_Creek   Grand_Turk   Jujuy         Martinique     Nassau       Port_of_Spain   Santo_Domingo  Thunder_Bay
Bahia           Catamarca      Denver         Grenada      Juneau        Matamoros      New_York     Porto_Velho     Sao_Paulo      Tijuana
Bahia_Banderas  Cayenne        Detroit        Guadeloupe   Kentucky      Mazatlan       Nipigon      Puerto_Rico     Scoresbysund   Toronto
Barbados        Cayman         Dominica       Guatemala    Knox_IN       Mendoza        Nome         Punta_Arenas    Shiprock       Tortola
Belem           Chicago        Edmonton       Guayaquil    Kralendijk    Menominee      Noronha      Rainy_River     Sitka          Vancouver

root@openmediavault:/usr/share/zoneinfo/America# nano moncton    #<-----Found that this file was empty (It's the time zone I use)
root@openmediavault:/usr/share/zoneinfo/America# nano Jamaica    #<-----That one contained data
root@openmediavault:/usr/share/zoneinfo/America# nano Montreal   #<-----That one contained data too. So Moncton must be broken.
root@openmediavault:/usr/share/zoneinfo/America# dpkg-query -S /usr/share/zoneinfo/America/Moncton  
tzdata: /usr/share/zoneinfo/America/Moncton      #Found the Package for Moncton. It's tzdata.
root@openmediavault:/usr/share/zoneinfo/America# apt-get install --reinstall tzdata
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 0 not upgraded.
Need to get 0 B/263 kB of archives.
After this operation, 0 B of additional disk space will be used.
Preconfiguring packages ...
(Reading database ... 48053 files and directories currently installed.)
Preparing to unpack .../tzdata_2020a-0+deb10u1_all.deb ...
Unpacking tzdata (2020a-0+deb10u1) over (2020a-0+deb10u1) ...
Setting up tzdata (2020a-0+deb10u1) ...

Current default time zone: 'America/Moncton'
Local time is now:      Fri Jun 19 01:14:13 ADT 2020.
Universal Time is now:  Fri Jun 19 04:14:13 UTC 2020.
Run 'dpkg-reconfigure tzdata' if you wish to change it.

root@openmediavault:/usr/share/zoneinfo/America#reboot
```

Everything was back to normal after that!!! 😀 

Thanks for the hint Volker! Appreciate it.

Help found here: 
https://unix.stackexchange.com/questions/512674/debian-restore-a-timezone-file
Got hints from here:
Volker
[Google Search : "PHP Fatal error" "strftime" "Timezone database is corrupt"](https://www.google.com/search?rlz=1C1GGRV_enCA749CA749&sxsrf=ALeKk006pLJKCV_d8BsL1UphvdY-36Pz_w%3A1592572981616&ei=NbzsXraIJZCa_Qaw2buACQ&q=%22PHP+Fatal+error%22+%22strftime%22+%22Timezone+database+is+corrupt%22&oq=%22PHP+Fatal+error%22+%22strftime%22+%22Timezone+database+is+corrupt%22&gs_lcp=CgZwc3ktYWIQAzoECAAQR1CswgxYkeAMYJTiDGgAcAN4AIABdIgBrwOSAQMxLjOYAQCgAQGqAQdnd3Mtd2l6&sclient=psy-ab&ved=0ahUKEwj29uPW_I3qAhUQTd8KHbDsDpAQ4dUDCAw&uact=5)
