### ISSUE TITLE
AttributeError: module 'openmediavault' has no attribute 'bool'

### ISSUE THREAD

**Issue by ThisIsAreku** [openmediavault/openmediavault#854]
After updating from `5.5.16-1` to `5.5.17-1`, I face this issue when appying changes, either in the WebUI or with `omv-salt`

```
Traceback (most recent call last):
  File "/usr/sbin/omv-salt", line 25, in <module>
    import openmediavault.log
  File "/usr/lib/python3/dist-packages/openmediavault/__init__.py", line 23, in <module>
    import openmediavault.settings
  File "/usr/lib/python3/dist-packages/openmediavault/settings.py", line 155, in <module>
    Environment.load()
  File "/usr/lib/python3/dist-packages/openmediavault/settings.py", line 76, in load
    Environment.set(m.group(2), m.group(4))
  File "/usr/lib/python3/dist-packages/openmediavault/settings.py", line 151, in set
    return env_var.value if env_var else None
  File "/usr/lib/python3/dist-packages/openmediavault/settings.py", line 44, in __bool__
    return openmediavault.bool(self.value)
AttributeError: module 'openmediavault' has no attribute 'bool'
```
It seems that the `bool` function is defined after the import of `settings.py` so it's not defined at the time it's called in

**Comment by votdev** [comment]
Fixed in `openmediavault 5.5.17-2`.
