### ISSUE TITLE
Failed to connect to socket: No such file or directory

### ISSUE THREAD

**Issue by Systemac** [openmediavault/openmediavault#967]
After installing msmtp, i see that the systyem want to uninstall openmediavault.... I try to stop it but too late...

I try to apt-get install --reinstall openmediavault but this error appear : 

Paramétrage de openmediavault (5.5.23-1) ...
Creating configuration database ...
Migrating configuration database ...
Setting up Salt environment ...
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    load_entry_point('salt==3002.2', 'console_scripts', 'salt-call')()
  File "/usr/lib/python3/dist-packages/salt/scripts.py", line 437, in salt_call
    import salt.cli.call
  File "/usr/lib/python3/dist-packages/salt/cli/call.py", line 6, in <module>
    import salt.cli.caller
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 15, in <module>
    import salt.minion
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 26, in <module>
    import salt.crypt
  File "/usr/lib/python3/dist-packages/salt/crypt.py", line 31, in <module>
    import salt.utils.rsax931
  File "/usr/lib/python3/dist-packages/salt/utils/rsax931.py", line 138, in <module>
    libcrypto = _init_libcrypto()
  File "/usr/lib/python3/dist-packages/salt/utils/rsax931.py", line 91, in _init_libcrypto
    libcrypto = _load_libcrypto()
  File "/usr/lib/python3/dist-packages/salt/utils/rsax931.py", line 84, in _load_libcrypto
    return cdll.LoadLibrary(_find_libcrypto())
  File "/usr/lib/python3/dist-packages/salt/utils/rsax931.py", line 76, in _find_libcrypto
    raise OSError("Cannot locate OpenSSL libcrypto")
OSError: Cannot locate OpenSSL libcrypto
dpkg: erreur de traitement du paquet openmediavault (--configure) :
 installed openmediavault package post-installation script subprocess returned error exit status 1
Des erreurs ont été rencontrées pendant l'exécution :
 openmediavault
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by ryecoaaron** [comment]
Please post in the forum.  There are many more people that will see this and be able to possible help clean up your mess.  https://forum.openmediavault.org/wsc/

**Comment by votdev** [comment]
Why do you want to install msmtp? If you've enabled notifications in OMV, then postfix will send emails for you. If you want to have a CLI command, `mail` is what you can use.

**Comment by Systemac** [comment]
I wanted to go too fast, and was surprised not to have an email from fail2ban ... So I completely forgot that we could do it via notifications ... I punished myself by reinstalling, thanks to  you for having answered, knowing that the subject is closed ...
